// spec §21 collocations with awkward/wrong alternatives used by the evaluator.
export type CollocationSeed = { slug: string; collocation: string; meaning: string; register: string; example: string; awkwardAlternatives: string[] };

const C = (slug: string, collocation: string, meaning: string, example: string, awkwardAlternatives: string[], register = 'professional'): CollocationSeed =>
  ({ slug, collocation, meaning, register, example, awkwardAlternatives });

export const COLLOCATIONS: CollocationSeed[] = [
  C('col-make-decision', 'make a decision', 'decide', 'We need to make a decision by Friday.', ['do a decision', 'take a decision*']),
  C('col-take-risk', 'take a risk', 'accept risk', 'It\'s worth taking a risk on this hire.', ['do a risk', 'make a risk']),
  C('col-raise-concern', 'raise a concern', 'bring up a worry', 'I want to raise a concern about the timeline.', ['make a concern', 'put a concern']),
  C('col-deliver-results', 'deliver results', 'produce outcomes', 'She consistently delivers results.', ['do results', 'give results']),
  C('col-meet-deadline', 'meet a deadline', 'finish on time', 'We met the deadline.', ['reach the deadline', 'do the deadline']),
  C('col-reach-agreement', 'reach an agreement', 'arrive at terms', 'Both sides reached an agreement.', ['make an agreement*', 'do an agreement']),
  C('col-hold-meeting', 'hold a meeting', 'conduct a meeting', 'We\'ll hold a review meeting Thursday.', ['make a meeting*', 'do a meeting']),
  C('col-make-progress', 'make progress', 'advance', 'We\'re making steady progress.', ['do progress', 'get progress']),
  C('col-take-responsibility', 'take responsibility', 'own an outcome', 'I take responsibility for the delay.', ['do responsibility', 'make responsibility']),
  C('col-give-presentation', 'give a presentation', 'present formally', 'She gave a presentation to the board.', ['make a presentation*', 'do a presentation*']),
  C('col-ask-question', 'ask a question', 'inquire', 'Let me ask a question.', ['make a question', 'put a question*']),
  C('col-answer-question', 'answer a question', 'respond', 'Can you answer this question?', ['reply a question', 'respond a question']),
  C('col-keep-promise', 'keep a promise', 'honour a commitment', 'We always keep our promises.', ['hold a promise', 'maintain a promise']),
  C('col-pay-attention', 'pay attention', 'focus', 'Pay attention to the details.', ['give attention', 'make attention']),
  C('col-take-advantage', 'take advantage of', 'use an opportunity', 'Take advantage of the discount.', ['make advantage', 'get advantage*']),
  C('col-make-effort', 'make an effort', 'try deliberately', 'Make an effort to understand their constraints.', ['do an effort', 'give an effort']),
  C('col-have-impact', 'have an impact', 'create effect', 'The change had a real impact.', ['make an impact*', 'do an impact']),
  C('col-gain-traction', 'gain traction', 'start succeeding', 'The product is gaining traction.', ['get traction*', 'make traction']),
  C('col-build-rapport', 'build rapport', 'create connection', 'Build rapport before selling.', ['make rapport', 'create rapport*']),
  C('col-run-meeting', 'run a meeting', 'lead a meeting', 'Who\'s running the meeting?', ['do a meeting', 'conduct a meeting*']),
  C('col-launch-product', 'launch a product', 'release to market', 'We launch the product in March.', ['open a product', 'start a product*']),
  C('col-cut-costs', 'cut costs', 'reduce expenses', 'We need to cut costs this quarter.', ['reduce costs*', 'chop costs']),
  C('col-drive-growth', 'drive growth', 'cause growth', 'Retention drives growth.', ['make growth', 'push growth*']),
  C('col-secure-funding', 'secure funding', 'obtain investment', 'We secured funding last month.', ['get funding*', 'obtain funding*']),
  C('col-set-expectation', 'set expectations', 'define what\'s realistic', 'Set expectations early with clients.', ['make expectations', 'fix expectations']),
  C('col-draw-line', 'draw a line', 'set a boundary', 'We have to draw a line somewhere.', ['make a line', 'pull a line']),
  C('col-file-complaint', 'file a complaint', 'formally complain', 'The client filed a complaint.', ['make a complaint*', 'do a complaint']),
  C('col-issue-refund', 'issue a refund', 'process a refund', 'We issued a full refund.', ['give a refund*', 'make a refund']),
  C('col-sign-contract', 'sign a contract', 'execute an agreement', 'They signed the contract today.', ['do a contract', 'close a contract*']),
  C('col-mitigate-risk', 'mitigate risk', 'reduce exposure', 'A fallback plan mitigates the risk.', ['reduce risk*', 'lower risk*']),
  C('col-build-trust', 'build trust', 'earn confidence', 'Consistency builds trust.', ['make trust', 'create trust*']),
  C('col-earn-reputation', 'earn a reputation', 'become known for', 'They earned a reputation for reliability.', ['make a reputation', 'get a reputation*']),
  C('col-lose-face', 'lose face', 'be embarrassed publicly', 'Nobody wants to lose face in the meeting.', ['lose prestige*'], 'neutral'),
  C('col-save-face', 'save face', 'preserve dignity', 'Give them a way to save face.', ['keep face*'], 'neutral'),
  C('col-keep-word', 'keep one\'s word', 'honour a promise', 'We kept our word on delivery.', ['hold one\'s word', 'keep promise*']),
  C('col-take-stance', 'take a stance', 'adopt a position', 'We took a firm stance on pricing.', ['make a stance', 'take a stand*']),
  C('col-win-bid', 'win a bid', 'be awarded the contract', 'We won the bid on value.', ['gain a bid', 'take a bid*']),
  C('col-submit-proposal', 'submit a proposal', 'send an offer', 'We submitted the proposal Monday.', ['send a proposal*', 'give a proposal']),
  C('col-hit-target', 'hit a target', 'achieve the goal', 'The team hit its targets.', ['reach a target*', 'achieve a target*']),
  C('col-miss-target', 'miss a target', 'fail to reach it', 'We missed the Q3 target.', ['fail the target', 'lose the target']),
  C('col-exceed-expectation', 'exceed expectations', 'do better than expected', 'The release exceeded expectations.', ['cross expectations', 'over expectations']),
  C('col-fall-short', 'fall short of', 'fail to reach', 'Revenue fell short of projections.', ['miss short', 'short of target*']),
  C('col-do-business', 'do business', 'engage commercially', 'They\'re easy to do business with.', ['make business*']),
  C('col-conduct-review', 'conduct a review', 'perform a review', 'We conducted a thorough review.', ['do a review*', 'make a review*']),
  C('col-pose-threat', 'pose a threat', 'present a danger', 'The discount poses a threat to margin.', ['make a threat', 'give a threat']),
  C('col-voice-opinion', 'voice an opinion', 'state a view', 'Everyone voiced their opinions.', ['say an opinion', 'tell an opinion*']),
  C('col-reach-consensus', 'reach a consensus', 'arrive at agreement', 'The team reached a consensus.', ['make consensus', 'get consensus*']),
  C('col-break-deadlock', 'break a deadlock', 'unstick a negotiation', 'A non-price concession broke the deadlock.', ['solve a deadlock', 'end a deadlock*']),
  C('col-play-role', 'play a role', 'serve a function', 'Trust plays a role in pricing.', ['do a role*', 'make a role']),
  C('col-take-turn', 'take a turn', 'change direction suddenly', 'The negotiation took a turn.', ['make a turn*'], 'neutral'),
  C('col-make-case', 'make a case', 'argue for something', 'Make the case for your budget.', ['do a case', 'present a case*']),
  C('col-put-forward', 'put forward a proposal', 'submit for consideration', 'They put forward a revised proposal.', ['propose*', 'forward a proposal']),
  C('col-withdraw-offer', 'withdraw an offer', 'retract it', 'They withdrew the offer.', ['take back an offer*', 'cancel the offer*']),
  C('col-reject-categorically', 'reject outright', 'refuse completely', 'The clause was rejected outright.', ['reject completely*']),
  C('col-soften-blow', 'soften the blow', 'ease bad news', 'A discount softened the blow of the price rise.', ['ease the blow*']),
  C('col-gauge-interest', 'gauge interest', 'measure enthusiasm', 'Let\'s gauge interest before building.', ['measure interest*']),
  C('col-spark-debate', 'spark debate', 'trigger discussion', 'The proposal sparked debate.', ['ignite debate*', 'start debate*']),
  C('col-resolve-issue', 'resolve an issue', 'fix a problem', 'We resolved the issue overnight.', ['solve an issue*', 'fix an issue*']),
  C('col-address-concern', 'address a concern', 'respond to a worry', 'Let me address your concern directly.', ['answer a concern', 'resolve a concern*']),
  C('col-set-precedent', 'set a precedent', 'establish a pattern others follow', 'Discounts set a dangerous precedent.', ['make a precedent']),
  C('col-strike-balance', 'strike a balance', 'find middle ground', 'We struck a balance between cost and quality.', ['find a balance*', 'make a balance']),
  C('col-shoulder-burden', 'shoulder the burden', 'carry the weight', 'Our team shoulders the support burden.', ['carry the burden*', 'bear the burden*']),
  C('col-open-door', 'open the door to', 'enable', 'This partnership opens the door to new markets.', ['open doors for*']),
  C('col-close-gap', 'close the gap', 'reduce the difference', 'The discount closed the gap on price.', ['bridge the gap*']),
  C('col-bridge-gap', 'bridge the gap', 'connect two sides', 'The pilot bridges the gap between demo and rollout.', ['close the gap*']),
];
