// spec §17 — every topic in the grammar curriculum, each lesson in the required
// structure: concept → why → rule → simple/natural/business examples → common
// Indian-English mistakes → speaking exercise → writing exercise → quiz →
// real-world use → review handled by SRS.

export type QuizItem = { q: string; options: string[]; answer: number; explanation: string };
export type LessonSeed = {
  slug: string; topic: string; skillSlug: string;
  concept: string; whyItMatters: string; rule: string;
  simpleExamples: string[]; naturalExamples: string[]; businessExamples: string[];
  indianEnglishMistakes: { wrong: string; right: string; note: string }[];
  speakingPrompt: string; writingPrompt: string;
  quiz: QuizItem[]; realWorldUse: string;
};

const L = (
  slug: string, topic: string, skillSlug: string,
  concept: string, whyItMatters: string, rule: string,
  simpleExamples: [string, string, string], naturalExamples: [string, string, string],
  businessExamples: [string, string, string],
  indianEnglishMistakes: { wrong: string; right: string; note: string }[],
  speakingPrompt: string, writingPrompt: string,
  quiz: [QuizItem, QuizItem, QuizItem, QuizItem],
  realWorldUse: string,
): LessonSeed => ({
  slug, topic, skillSlug, concept, whyItMatters, rule,
  simpleExamples: [...simpleExamples], naturalExamples: [...naturalExamples], businessExamples: [...businessExamples],
  indianEnglishMistakes, speakingPrompt, writingPrompt, quiz: [...quiz], realWorldUse,
});

const Q = (q: string, options: string[], answer: number, explanation: string): QuizItem =>
  ({ q, options, answer, explanation });

export const GRAMMAR_LESSONS: LessonSeed[] = [
  L('lesson-parts-of-speech', 'Parts of Speech', 'parts-of-speech',
    'Every word plays a role: noun, verb, adjective, adverb, pronoun, preposition, conjunction, determiner.',
    'You cannot fix a sentence until you can name what each word is doing.',
    'Classify a word by its job in the sentence, not the word itself — "run" can be a verb or a noun.',
    ['Dogs bark.', 'The quick fox jumped.', 'She sings beautifully.'],
    ['I took a long walk after lunch.', 'The meeting ran way over time.', "That's a really tough call."],
    ['The quarterly report is due Friday.', 'She presented the findings clearly.', 'Revenue grew steadily.'],
    [{ wrong: 'He is very intelligence.', right: 'He is very intelligent.', note: 'Intelligence is a noun; the adjective is intelligent.' }],
    'Describe your morning routine, naming one noun, verb and adjective you use.',
    'Write three sentences about your job; label the noun, verb and adjective in each.',
    [Q('In "She quickly answered", "quickly" is a…', ['noun', 'verb', 'adverb', 'adjective'], 2, 'It modifies the verb "answered".'),
     Q('"Run" in "a daily run" is a…', ['verb', 'noun', 'adjective', 'adverb'], 1, 'Here it names a thing — the activity.'),
     Q('Which word is a determiner?', ['quickly', 'the', 'happy', 'and'], 1, '"The" introduces a noun phrase.'),
     Q('"And" is a…', ['preposition', 'pronoun', 'conjunction', 'adverb'], 2, 'It joins clauses.')],
    'Every other grammar skill builds on naming word roles.'),
  L('lesson-nouns', 'Nouns', 'nouns',
    'Nouns name people, places, things and ideas; they split into countable and uncountable.',
    'Article and plural errors usually trace back to miscounting nouns.',
    'Uncountable nouns (information, advice, work, feedback) never take a/an or -s.',
    ['I have a dog.', 'Water is essential.', 'She gave me advice.'],
    ['I need some feedback on this draft.', 'There isn\'t much traffic today.', 'We bought new equipment.'],
    ['The information is in the appendix.', 'His advice saved us a week.', 'We received positive feedback.'],
    [{ wrong: 'I need an information.', right: 'I need some information.', note: 'Information is uncountable.' },
     { wrong: 'She gave me many advices.', right: 'She gave me a lot of advice.', note: 'Advice is uncountable.' }],
    'List five things on your desk; say which are countable.',
    'Write a sentence each using "information", "advice" and "feedback" correctly.',
    [Q('Which is uncountable?', ['chair', 'luggage', 'apple', 'idea'], 1, 'Luggage takes no plural.'),
     Q('Correct form:', ['an advice', 'some advice', 'advices', 'a advice'], 1, 'Uncountable — use "some".'),
     Q('"News" is…', ['plural', 'uncountable singular', 'countable', 'adjective'], 1, '"The news is good."'),
     Q('Correct:', ['many informations', 'much information', 'an information', 'informations'], 1, 'Uncountable + much.')],
    'Uncountable nouns are the single most common Indian-English slip.'),
  L('lesson-pronouns', 'Pronouns', 'pronouns',
    'Pronouns replace nouns: subject (I), object (me), possessive (my/mine), reflexive (myself).',
    'Wrong pronoun case ("between you and I") is noticed immediately by fluent speakers.',
    'Use subject pronouns as subjects, object pronouns after verbs and prepositions.',
    ['She called me.', 'It is mine.', 'He did it himself.'],
    ['Just between you and me, the deal is shaky.', 'They introduced themselves.', 'Nobody saw it but us.'],
    ['Please send the file to Priya or me.', 'The client signed it themselves.', 'My team and I reviewed it.'],
    [{ wrong: 'Myself will handle it.', right: 'I will handle it myself.', note: '"Myself" cannot be a subject.' }],
    'Introduce a colleague using three different pronoun types.',
    'Write a two-line handover note using object and possessive pronouns.',
    [Q('Choose: ___ am ready.', ['Me', 'I', 'Mine', 'Myself'], 1, 'Subject position needs "I".'),
     Q('"between you and ___"', ['I', 'me', 'myself', 'mine'], 1, 'After a preposition use object form.'),
     Q('Correct:', ['Her and I went', 'She and I went', 'Me and her went', 'Her and me went'], 1, 'Both are subjects.'),
     Q('"It\'s ___" (possessive):', ['their\'s', 'theirs', 'theres', 'their'], 1, 'Possessive pronoun, no apostrophe.')],
    'Client emails read instantly more professional with correct pronoun case.'),
  L('lesson-articles', 'Articles', 'articles',
    'a/an for first mention or non-specific; the for known/specific; zero article for general plurals and uncountables.',
    'Article omission is the most recognisable Indian-English marker in speech and email.',
    'a + consonant sound, an + vowel sound; the when both sides know which one; no article for general statements.',
    ['I saw a bird.', 'The bird was blue.', 'Dogs are loyal.'],
    ['I grabbed a coffee on the way in.', 'The proposal we sent yesterday got approved.', 'Honesty matters here.'],
    ['We hired a consultant.', 'The contract is signed.', 'Innovation drives growth.'],
    [{ wrong: 'I went to office.', right: 'I went to the office.', note: 'Specific known place takes "the" (idioms like school/hospital aside).' },
     { wrong: 'He is a honest man.', right: 'He is an honest man.', note: '"Hour"/"honest" start with vowel sounds → an.' }],
    'Describe your route to work using a/an/the correctly five times.',
    'Write a three-line status update; circle every article choice.',
    [Q('___ honest answer', ['a', 'an', 'the', 'no article'], 1, 'h is silent → an.'),
     Q('I went to ___ university.', ['a', 'an', 'the', 'no article'], 0, '"university" starts with a /j/ consonant sound.'),
     Q('___ honesty is rare.', ['A', 'An', 'The', 'No article'], 3, 'Abstract quality, general sense → zero article.'),
     Q('Choose: I read ___ book you recommended.', ['a', 'an', 'the', 'no article'], 2, 'Both speaker and listener know which book.')],
    'Articles decide whether your English "sounds right" before anyone analyses grammar.'),
  L('lesson-determiners', 'Determiners', 'determiners',
    'Determiners fix which/how many: this, some, much, few, each, every.',
    'Much/many and few/little errors change your meaning.',
    'much/little + uncountable; many/few + countable; each/every + singular.',
    ['I have many friends.', 'There is little time.', 'Each student passed.'],
    ['We don\'t have much bandwidth this sprint.', 'Few clients complained.', 'Every report was on time.'],
    ['Many stakeholders attended.', 'We have little room for error.', 'Each deliverable has an owner.'],
    [{ wrong: 'Much people attended.', right: 'Many people attended.', note: 'People is countable → many.' }],
    'Compare your workload today vs last month using much/many/few/little.',
    'Write two sentences with "each" and "every" about your team.',
    [Q('___ time do we have?', ['Many', 'Much', 'Few', 'A few'], 1, 'Time is uncountable.'),
     Q('___ employee signed.', ['Every', 'All', 'Much', 'Many'], 0, 'Every + singular verb.'),
     Q('"a few" vs "few": "Few understood" means…', ['some did', 'almost none did', 'everyone did', 'none'], 1, 'Few = almost none (negative sense).'),
     Q('Correct:', ['much mistakes', 'many mistakes', 'a little mistakes', 'a mistakes'], 1, 'Mistakes are countable.')],
    'Precise quantity words make status updates credible.'),
  L('lesson-adjectives', 'Adjectives', 'adjectives-adverbs',
    'Adjectives describe nouns and have a natural order: opinion, size, age, shape, colour, origin, material.',
    'Order errors ("red big ball") instantly mark non-native speech.',
    'Adjectives go before nouns or after be/seem; never take -s ("the reds cars" ✗).',
    ['It is a big red ball.', 'She wore a beautiful old Indian sari.', 'The soup is hot.'],
    ['That was a brilliant little trick.', 'We drove through a quiet residential area.', 'He gave a long detailed answer.'],
    ['We need a scalable cloud-based solution.', 'It was a thorough technical review.', 'She gave a concise verbal summary.'],
    [{ wrong: 'He is more smarter.', right: 'He is smarter.', note: 'Double comparison is wrong.' }],
    'Describe your phone with three ordered adjectives.',
    'Describe your product in two sentences with correctly ordered adjectives.',
    [Q('Correct order:', ['a wooden old table', 'an old wooden table', 'a table old wooden', 'an wooden old table'], 1, 'Age before material.'),
     Q('Adjectives in English…', ['take -s for plurals', 'never take -s', 'take -es', 'agree in gender'], 1, 'No agreement in English.'),
     Q('Which is correct?', ['a interesting book', 'an interesting book', 'interesting an book', 'the interest book'], 1, 'an + vowel sound.'),
     Q('"seem" is followed by…', ['adverb', 'adjective', 'noun only', 'gerund'], 1, '"It seems difficult".')],
    'Ordered adjectives make product demos sound fluent.'),
  L('lesson-adverbs', 'Adverbs', 'adjectives-adverbs',
    'Adverbs modify verbs, adjectives, other adverbs and whole sentences.',
    'Putting an adjective where an adverb belongs ("he drives good") is a frequent slip.',
    'Manner adverbs usually take -ly; hard/fast/late keep the same form; place them carefully.',
    ['She sings well.', 'He drives carefully.', 'They arrived late.'],
    ['The client called unexpectedly early.', 'I completely forgot about the call.', 'She handled it really well.'],
    ['The team performed exceptionally well.', 'We nearly missed the deadline.', 'Sales rose sharply last quarter.'],
    [{ wrong: 'He explained it very good.', right: 'He explained it very well.', note: 'Modify the verb with an adverb.' }],
    'Describe how you work using well/carefully/quickly/clearly.',
    'Write two sentences about a project using "nearly" and "completely".',
    [Q('He works ___.', ['good', 'well', 'nice', 'finey'], 1, 'Well is the adverb of good.'),
     Q('"hard" as an adverb means…', ['with difficulty', 'intensely', 'slowly', 'barely'], 1, '"She works hard."'),
     Q('"hardly" means…', ['intensely', 'almost not', 'with effort', 'solidly'], 1, 'Hardly = almost not — a trap word.'),
     Q('Choose: She speaks very ___.', ['fluent', 'fluently', 'fluentness', 'fluenting'], 1, 'Adverb modifies speaks.')],
    'Adverb choice decides whether "hard" and "hardly" say opposite things.'),
  L('lesson-prepositions', 'Prepositions', 'prepositions',
    'Prepositions link words to time, place and relations; many are fixed by the verb (depend on, interested in).',
    'Wrong prepositions ("discuss about", "married with") are the #1 Indian-English tell.',
    'Learn prepositions attached to their verb/adjective/noun — never alone.',
    ['The meeting is at 9.', 'She lives in Chennai.', 'I depend on you.'],
    ['I\'m really into this project right now.', 'We arrived at the airport just in time.', 'He apologised for the delay.'],
    ['We agreed on the terms.', 'The report focuses on retention.', 'She is responsible for delivery.'],
    [{ wrong: 'We discussed about it.', right: 'We discussed it.', note: 'discuss takes a direct object.' },
     { wrong: 'I am married with her.', right: 'I am married to her.', note: 'married to, not with.' },
     { wrong: 'He ordered for coffee.', right: 'He ordered coffee.', note: 'order takes a direct object.' }],
    'Say three sentences using depend on, focus on, apologise for.',
    'Write a short note with agree on, responsible for, interested in.',
    [Q('interested ___', ['on', 'in', 'at', 'for'], 1, 'Fixed: interested in.'),
     Q('depend ___', ['of', 'on', 'in', 'with'], 1, 'depend on.'),
     Q('We discussed ___ the issue.', ['about', 'on', '— (no preposition)', 'over'], 2, 'discuss is transitive.'),
     Q('good ___ negotiating', ['in', 'at', 'on', 'for'], 1, 'good at.')],
    'Preposition accuracy is the fastest fluency signal in business email.'),
  L('lesson-conjunctions', 'Conjunctions', 'conjunctions',
    'Coordinators (and, but, so, yet) join equals; subordinators (because, although, when, if) join a dependent clause to a main one.',
    'Subordination is how simple English becomes fluent English.',
    'One subordinator per clause — don\'t double up ("although… but" ✗).',
    ['I stayed, and she left.', 'He was tired but happy.', 'We waited because it rained.'],
    ['Although it was late, we kept talking.', 'I\'ll call you when I land.', 'She left early, so we wrapped up.'],
    ['Although costs rose, margins held.', 'We paused hiring because revenue dipped.', 'If the client agrees, we start Monday.'],
    [{ wrong: 'Although it rained, but we played.', right: 'Although it rained, we played.', note: 'Never although+but together.' }],
    'Link two ideas about your week using although, because and so.',
    'Write a project update sentence starting with "Although".',
    [Q('Choose: ___ it was expensive, we bought it.', ['Although', 'But', 'So', 'And'], 0, 'Although introduces the concession.'),
     Q('Correct:', ['Because I was tired, so I slept.', 'Because I was tired, I slept.', 'Because tired I slept.', 'I slept because tired.'], 1, 'No double connector.'),
     Q('"so" in "It rained, so we stayed" is…', ['subordinator', 'coordinator', 'preposition', 'adverb'], 1, 'Joins two equal clauses.'),
     Q('"yet" in "simple yet effective" shows…', ['addition', 'contrast', 'time', 'reason'], 1, 'Yet = but.')],
    'Subordinating conjunctions unlock complex, professional sentences.'),
  L('lesson-auxiliary-verbs', 'Auxiliary Verbs', 'auxiliary-modal-verbs',
    'do/does/did, be and have carry questions, negatives and perfect/continuous forms.',
    'Almost every tense and question depends on getting the auxiliary right.',
    'The auxiliary carries tense and agreement; the main verb stays in base form after do/does/did.',
    ['She does not like tea.', 'Did you eat?', 'They are working.'],
    ['I didn\'t see the memo.', 'Do you know where he went?', 'We haven\'t finished yet.'],
    ['Did the client approve the scope?', 'We are reviewing the contract.', 'I have completed the audit.'],
    [{ wrong: 'I didn\'t went.', right: 'I didn\'t go.', note: 'did already carries past tense — use base verb.' },
     { wrong: 'Does he plays?', right: 'Does he play?', note: 'After does, base form.' }],
    'Ask three past questions correctly: Did you…? Did she…? Did they…?',
    'Write three negative sentences with didn\'t + base verb.',
    [Q('Did you ___ him?', ['saw', 'see', 'seen', 'seeing'], 1, 'Base form after did.'),
     Q('She ___ finished.', ['have', 'has', 'is', 'do'], 1, 'Third person singular → has.'),
     Q('Correct negative:', ['He don\'t know.', 'He doesn\'t knows.', 'He doesn\'t know.', 'He not know.'], 2, 'doesn\'t + base.'),
     Q('"___ they arrived?" is wrong because…', ['do should be did', 'arrived should be arrive after do/does/did in questions', 'they is wrong', 'nothing wrong'], 1, 'Do you…? + base verb.')],
    'Auxiliaries are the engine of every question you will ever ask a client.'),
  L('lesson-modal-verbs', 'Modal Verbs', 'auxiliary-modal-verbs',
    'can/could/may/might/must/should/would express ability, permission, probability, advice and politeness.',
    'Modal choice controls politeness — "Send it" vs "Could you send it?".',
    'Modal + base verb; could/would/might soften; must/have to for obligation; should for advice.',
    ['I can swim.', 'You should rest.', 'It might rain.'],
    ['Could you send that over?', 'We might need more time.', 'You must see this.'],
    ['Could you clarify the timeline?', 'We should escalate this.', 'The vendor might deliver late.'],
    [{ wrong: 'I can able to do it.', right: 'I can do it. / I am able to do it.', note: 'Never can + able together.' },
     { wrong: 'You must to go.', right: 'You must go.', note: 'Modal + base verb, no to.' }],
    'Make the same request three ways: direct, polite, very polite.',
    'Write two sentences advising a teammate with should and might.',
    [Q('Most polite:', ['Send it.', 'You must send it.', 'Could you send it?', 'Send it now.'], 2, 'Could you… is the standard polite request.'),
     Q('Modal + ___', ['to go', 'going', 'base form', 'past form'], 2, 'Modal + base verb.'),
     Q('"You ___ apologize" (advice):', ['must', 'should', 'can', 'may'], 1, 'should = advice; must = obligation.'),
     Q('Choose: ___ I come in? (permission)', ['Should', 'May', 'Must', 'Will'], 1, 'May = formal permission.')],
    'Modals are how polite English works — this is register, not grammar trivia.'),
  L('lesson-verb-forms', 'Verb Forms', 'basic-verb-forms',
    'Every verb has base, past, past participle, -ing and third-person -s forms.',
    'Irregular past forms (go/went/gone) are the raw material of all past-tense speech.',
    'After do/does/did/modals use the base form; perfect tenses need the participle.',
    ['go–went–gone', 'write–wrote–written', 'I have eaten.'],
    ['I\'ve already seen that email.', 'He took the earlier flight.', 'She has written three proposals.'],
    ['The deal was closed last week.', 'We have chosen the vendor.', 'Costs have risen sharply.'],
    [{ wrong: 'I have went there.', right: 'I have gone there.', note: 'Perfect tenses need the participle "gone".' }],
    'Say the three forms of: take, make, see, give, know, think.',
    'Write three present-perfect sentences using gone, written, chosen.',
    [Q('have + ___', ['went', 'go', 'gone', 'going'], 2, 'Past participle after have.'),
     Q('Past of "teach":', ['teached', 'taught', 'teachen', 'teacht'], 1, 'Irregular: taught.'),
     Q('Correct:', ['He has wrote', 'He has written', 'He has wrote', 'He have written'], 1, 'has + written.'),
     Q('After "did" use…', ['past', 'participle', 'base', 'ing'], 2, 'Base form.')],
    'Every tense mistake is a verb-form mistake first.'),
  L('lesson-present-simple', 'Present Simple', 'present-simple',
    'Habits, facts, routines and schedules.',
    'It carries daily standups, product facts and general truth.',
    'Base verb; add -s/-es for he/she/it; negative/questions with do/does.',
    ['I work from home.', 'The sun rises in the east.', 'She plays tennis.'],
    ['The train leaves at six.', 'He checks email first thing.', 'We don\'t ship on Fridays.'],
    ['The team meets daily at ten.', 'Our product integrates with Slack.', 'She manages three accounts.'],
    [{ wrong: 'He go to office.', right: 'He goes to office.', note: 'Third-person -s.' },
     { wrong: 'I am agree.', right: 'I agree.', note: 'agree is stative — no continuous form.' }],
    'Describe your typical workday in five sentences.',
    'Write a four-sentence product description in present simple.',
    [Q('She ___ coffee.', ['drink', 'drinks', 'drinking', 'drank'], 1, 'Third-person -s.'),
     Q('Stative verbs like "know" take…', ['continuous', 'simple', 'perfect', 'passive'], 1, '"I know" not "I am knowing".'),
     Q('Question form:', ['Does he works?', 'Do he work?', 'Does he work?', 'Is he work?'], 2, 'does + base.'),
     Q('Present simple is NOT used for…', ['habits', 'facts', 'actions happening now', 'schedules'], 2, 'Ongoing action → present continuous.')],
    'Most workplace English is present simple — master it first.'),
  L('lesson-present-continuous', 'Present Continuous', 'present-continuous',
    'Actions in progress now and temporary situations.',
    'Separating "always" (simple) from "right now" (continuous) is a core fluency move.',
    'am/is/are + -ing; stative verbs (know, want, agree, need, belong) stay simple.',
    ['I am cooking.', 'She is reading.', 'They are sleeping.'],
    ['I\'m working on the report right now.', 'We\'re hiring this quarter.', 'It\'s getting late.'],
    ['We are onboarding two clients.', 'The team is finalising the proposal.', 'I am travelling next week for the summit.'],
    [{ wrong: 'I am having a car.', right: 'I have a car.', note: 'have (possession) is stative.' },
     { wrong: 'I am not understanding.', right: 'I don\'t understand.', note: 'understand is stative.' }],
    'Describe three things happening in your room right now.',
    'Write two sentences about current projects using present continuous.',
    [Q('Right now I ___ a call.', ['have', 'am having', 'had', 'will have'], 1, 'Action in progress (having = experiencing) can be continuous.'),
     Q('Which is correct?', ['I am knowing him.', 'I know him.', 'I am know him.', 'I knowing him.'], 1, 'Stative.'),
     Q('Temporary situation:', ['I live in Chennai.', 'I am living in Chennai this month.', 'I lived Chennai.', 'Chennai is living me.'], 1, 'Continuous = temporary.'),
     Q('are + ___', ['go', 'goes', 'going', 'gone'], 2, '-ing form.')],
    'Stative-vs-continuous is the most-tested Indian-English pattern — §42.'),
  L('lesson-past-simple', 'Past Simple', 'past-simple',
    'Completed actions at a finished time.',
    'Storytelling, status reports and incident reviews all run on past simple.',
    'verb+ed or irregular past; questions/negatives with did + BASE form.',
    ['I walked yesterday.', 'She called me.', 'We ate lunch.'],
    ['I saw the update this morning.', 'He left early on Friday.', 'We finished ahead of schedule.'],
    ['The client signed on Monday.', 'We shipped the release last week.', 'Q3 revenue grew 12%.'],
    [{ wrong: 'I didn\'t went.', right: 'I didn\'t go.', note: 'THE canonical fossilised error — did + base form.' },
     { wrong: 'Yesterday I go.', right: 'Yesterday I went.', note: 'Finished time marker needs past.' }],
    'Tell me three things you did last weekend.',
    'Write a three-line incident summary in past simple.',
    [Q('didn\'t + ___', ['went', 'go', 'gone', 'going'], 1, 'Base form after didn\'t.'),
     Q('Past of "bring":', ['brang', 'bringed', 'brought', 'broughten'], 2, 'Irregular: brought.'),
     Q('Correct:', ['Did you saw it?', 'Did you see it?', 'Did you seen it?', 'You saw it did?'], 1, 'did + base.'),
     Q('Choose: We ___ the contract yesterday.', ['sign', 'signed', 'have signed', 'signing'], 1, 'Finished time → past simple.')],
    '"didn\'t went" is the single highest-value fix in your error profile.'),
  L('lesson-past-continuous', 'Past Continuous', 'past-continuous',
    'An ongoing past action, often interrupted by a past-simple event.',
    'It frames stories: "I was driving when the call came."',
    'was/were + -ing; use for background, past simple for the interrupting event.',
    ['I was sleeping.', 'It was raining.', 'They were playing.'],
    ['I was cooking when the phone rang.', 'We were discussing the deal when she walked in.', 'He was driving too fast.'],
    ['I was presenting when the projector failed.', 'We were negotiating when procurement stepped in.', 'She was drafting the email when the client called.'],
    [{ wrong: 'When I was coming, he go.', right: 'When I was coming, he went.', note: 'Background continuous + interrupting simple.' }],
    'Describe what you were doing this time yesterday.',
    'Write two sentences: background action + interrupting event.',
    [Q('I ___ when he called.', ['cooked', 'was cooking', 'am cooking', 'cook'], 1, 'Ongoing background.'),
     Q('was/were + ___', ['base', 'past', '-ing', 'participle'], 2, '-ing.'),
     Q('Choose: While we ___, the server crashed.', ['deployed', 'were deploying', 'deploy', 'are deploying'], 1, 'Background = continuous.'),
     Q('Past continuous expresses…', ['completed action', 'ongoing past action', 'future plan', 'habit'], 1, 'Ongoing.')],
    'Incident reports need this pattern constantly.'),
  L('lesson-present-perfect', 'Present Perfect', 'present-perfect',
    'Past actions connected to now: experience, recent events, unfinished time.',
    'It answers "have you done X yet?" — the most common business question form.',
    'have/has + past participle; never with a finished time (say yesterday → past simple).',
    ['I have eaten.', 'She has visited Paris.', 'We have finished.'],
    ['I\'ve just sent the file.', 'Have you ever tried this?', 'We haven\'t heard back yet.'],
    ['The client has approved the budget.', 'I\'ve already reviewed the contract.', 'We have known them since 2019.'],
    [{ wrong: 'I have seen him yesterday.', right: 'I saw him yesterday.', note: 'Finished time → past simple, not perfect.' },
     { wrong: 'I am having three years of experience.', right: 'I have three years of experience.', note: 'Stative have → simple.' }],
    'Answer: three things you have done this week.',
    'Write two sentences with "just" and "yet".',
    [Q('I ___ him yesterday.', ['have seen', 'saw', 'see', 'had seen'], 1, 'Finished time → past simple.'),
     Q('have/has + ___', ['past', 'base', 'past participle', '-ing'], 2, 'Participle.'),
     Q('"yet" goes with…', ['affirmative perfect', 'negative/question perfect', 'past simple', 'present simple'], 1, '"Haven\'t finished yet".'),
     Q('Correct:', ['I have knew him for years', 'I have known him for years', 'I known him', 'I have knew'], 1, 'Participle "known".')],
    '"Have you reviewed it yet?" — you hear this daily.'),
  L('lesson-past-perfect', 'Past Perfect', 'past-simple',
    'The earlier of two past events: "The meeting had ended before I arrived."',
    'It orders past events clearly in reports and narratives.',
    'had + past participle for the earlier event.',
    ['She had left.', 'I had eaten before noon.', 'They had finished.'],
    ['The train had already gone when I reached the station.', 'I realised I had forgotten my keys.', 'He had never seen snow before that trip.'],
    ['The vendor had shipped before we cancelled.', 'We had warned the client earlier.', 'By the time I joined, the deal had closed.'],
    [{ wrong: 'I had went before he came.', right: 'I had gone before he came.', note: 'had + participle.' }],
    'Describe a time you arrived somewhere too late — what had already happened?',
    'Write two sentences ordering two past events with "had".',
    [Q('The earlier past event takes…', ['past simple', 'past continuous', 'past perfect', 'present perfect'], 2, 'had + participle.'),
     Q('Choose: When I arrived, the meeting ___.', ['ended', 'had ended', 'has ended', 'ends'], 1, 'Earlier event → past perfect.'),
     Q('had + ___', ['go', 'went', 'gone', 'going'], 2, 'Participle.'),
     Q('Correct:', ['I had ate', 'I had eaten', 'I had eat', 'I have had eaten'], 1, 'had + eaten.')],
    'Perfect tenses are what separate B1 storytellers from B2 ones.'),
  L('lesson-future-forms', 'Future Forms', 'future-forms',
    'will for decisions/predictions, going to for plans, present continuous for arrangements.',
    'Choosing the wrong future form changes certainty and tone.',
    'will = spontaneous/promise; going to = intention; present continuous = fixed arrangement.',
    ['I will call you.', 'It is going to rain.', 'I am meeting Sam tomorrow.'],
    ['I\'ll grab the next flight.', 'We\'re going to launch in March.', 'I\'m seeing the dentist at four.'],
    ['We will deliver by Friday — I promise.', 'We\'re going to expand the team.', 'I\'m presenting to the board on Thursday.'],
    [{ wrong: 'I will be going to office tomorrow.', right: 'I\'m going to the office tomorrow.', note: 'Fixed plan → going to/continuous, not double future.' }],
    'State one prediction (will), one plan (going to), one arrangement (continuous).',
    'Write a two-line schedule note for tomorrow.',
    [Q('Spontaneous decision at the door: "I ___ help you."', ['am going to', 'will', 'am helping', 'would'], 1, 'will for instant decisions.'),
     Q('Fixed arrangement:', ['I will meet', 'I am meeting him at 5', 'I going to meet', 'I might to meet'], 1, 'Present continuous.'),
     Q('"going to" expresses…', ['obligation', 'intention/plan', 'permission', 'past habit'], 1, 'Intention.'),
     Q('Choose: Look at the clouds — it ___ rain.', ['will', 'is going to', 'rains', 'is raining to'], 1, 'Evidence-based prediction → going to.')],
    'Promises to clients use will; plans use going to — the difference reads as confidence.'),
  L('lesson-questions', 'Questions', 'questions',
    'Yes/no (auxiliary inversion), wh- questions, subject questions and tag questions.',
    'Question quality is a negotiation and discovery skill, not just grammar.',
    'Auxiliary before subject; subject questions drop the auxiliary; tags flip polarity.',
    ['Do you like tea?', 'Where do you live?', 'It\'s ready, isn\'t it?'],
    ['Did she say when she\'d arrive?', 'Who called this morning?', 'You\'re joining the call, aren\'t you?'],
    ['What concerns you most about the proposal?', 'Who owns this deliverable?', 'The timeline works for you, doesn\'t it?'],
    [{ wrong: 'Why you are late?', right: 'Why are you late?', note: 'Invert the auxiliary.' },
     { wrong: 'What you are doing?', right: 'What are you doing?', note: 'Auxiliary before subject.' },
     { wrong: 'You are coming, no?', right: 'You\'re coming, aren\'t you?', note: '"no?" tags mark Indian English.' }],
    'Ask me five wh- questions about a project.',
    'Write three tag questions confirming meeting details.',
    [Q('Choose: Where ___ yesterday?', ['you went', 'did you went', 'did you go', 'you did go'], 2, 'did + base + inversion.'),
     Q('Subject question:', ['Who did call?', 'Who called?', 'Who does called?', 'Who is call?'], 1, 'Subject questions: no auxiliary.'),
     Q('Tag for "She left early":', ['didn\'t she', 'isn\'t she', 'doesn\'t she', 'no?'], 0, 'Past positive → didn\'t she.'),
     Q('"isn\'t it" used for "You will come" is…', ['correct', 'wrong — should be "won\'t you"', 'formal', 'plural'], 1, 'Tag copies the auxiliary.')],
    'Discovery calls are won by question quality — see §27.'),
  L('lesson-negation', 'Negation', 'negation',
    'Forming negatives with auxiliaries, not, never, nobody, nothing, nowhere.',
    'Double negatives and misplaced "not" flip meaning.',
    'One negator per clause; auxiliary + not + base verb.',
    ['I do not know.', 'She never lies.', 'Nobody came.'],
    ['I didn\'t get the memo.', 'There\'s nothing left.', 'We won\'t be late.'],
    ['We did not receive the invoice.', 'The report contains no errors.', 'Nobody flagged the risk.'],
    [{ wrong: 'I am not having any doubts.', right: 'I have no doubts. / I don\'t have any doubts.', note: 'Stative have → simple negative.' },
     { wrong: 'He didn\'t came.', right: 'He didn\'t come.', note: 'did + base, even in negatives.' }],
    'Say three things you don\'t do on weekends.',
    'Rewrite positively worded complaints using never/nobody/nothing correctly.',
    [Q('Choose: I ___ understand.', ['don\'t', 'doesn\'t', 'am not', 'no'], 0, 'do + not + base.'),
     Q('Correct:', ['He didn\'t went', 'He didn\'t go', 'He not go', 'He doesn\'t went'], 1, 'didn\'t + base.'),
     Q('"I don\'t know nothing" is…', ['emphatic and fine', 'a double negative — means the opposite', 'formal', 'correct'], 1, 'One negator only.'),
     Q('Negative of "She has arrived":', ['She hasn\'t arrived', 'She doesn\'t arrived', 'She no arrived', 'She didn\'t arrived'], 0, 'has + not + participle.')],
    'Contract language tolerates zero ambiguity in negation.'),
  L('lesson-subject-verb-agreement', 'Subject–Verb Agreement', 'subject-verb-agreement',
    'The verb agrees with its subject even when separated by long phrases.',
    '"The quality of the reports are…" is the classic professional writing slip.',
    'Find the true subject; ignore interrupting phrases; each/every/nobody are singular; there is/are agrees with what follows.',
    ['The list is long.', 'Each student passes.', 'There are three options.'],
    ['The quality of these reports is excellent.', 'Nobody in the team was late.', 'There\'s a problem with the build.'],
    ['The set of proposals was approved.', 'Each of the vendors has submitted.', 'There are several risks in this plan.'],
    [{ wrong: 'The list of items are ready.', right: 'The list of items is ready.', note: 'Subject is "list", singular.' }],
    'Say three sentences starting with "Each of the…".',
    'Write two sentences with a long subject phrase and correct singular verb.',
    [Q('The box of chocolates ___ empty.', ['are', 'is', 'were', 'be'], 1, 'Subject = box.'),
     Q('Each of the boys ___ a pen.', ['have', 'has', 'are having', 'having'], 1, 'Each → singular.'),
     Q('There ___ two reasons.', ['is', 'are', 'was', 'be'], 1, 'Agrees with "reasons".'),
     Q('Correct:', ['Mathematics are hard', 'Mathematics is hard', 'Mathematics have hard', 'Mathematics hard'], 1, '-ics subjects are singular.')],
    'Long-subject agreement is what separates careful professional writing.'),
  L('lesson-countable-uncountable', 'Countable & Uncountable', 'countable-uncountable',
    'Countable nouns pluralise and take a/many/few; uncountables take much/little and stay singular.',
    'Feedbacks, informations, softwares — these plurals don\'t exist.',
    'Abstract, mass and substance nouns are uncountable; count them with "pieces of" or quantifiers.',
    ['two apples', 'some water', 'a piece of news'],
    ['We got some useful feedback.', 'There isn\'t much work left.', 'He gave me two pieces of advice.'],
    ['We received valuable input.', 'There is little evidence for that claim.', 'No new software was installed.'],
    [{ wrong: 'We got many feedbacks.', right: 'We got a lot of feedback.', note: 'feedback is uncountable.' },
     { wrong: 'I need some informations.', right: 'I need some information.', note: 'information has no plural.' },
     { wrong: 'Install the softwares.', right: 'Install the software.', note: 'software is uncountable.' }],
    'Name five uncountable things in your work.',
    'Correct three sentences misusing informations/advices/feedbacks.',
    [Q('Correct:', ['many homeworks', 'much homework', 'a homework', 'homeworks'], 1, 'Uncountable.'),
     Q('"equipment" is…', ['countable', 'uncountable', 'plural', 'verb'], 1, 'Never "equipments".'),
     Q('Choose: ___ research shows…', ['Many', 'Much', 'A', 'These'], 1, 'Uncountable → much.'),
     Q('A countable alternative for "advice":', ['advices', 'a suggestion', 'advise', 'advisement'], 1, 'A suggestion.')],
    'Uncountable plurals are fossilised-error territory for Tamil speakers.'),
  L('lesson-comparatives', 'Comparatives', 'comparatives-superlatives',
    'Comparing two things: -er or more + adjective, than.',
    'Comparisons carry every sales and trade-off conversation.',
    'Short adjectives take -er; long ones take more; irregular: good→better, bad→worse, far→further.',
    ['This is bigger.', 'She is taller than me.', 'This book is better.'],
    ['This route is faster than that one.', 'It\'s more expensive than we expected.', 'The new version is much better.'],
    ['Our offer is more competitive.', 'Q4 was significantly better than Q3.', 'This design is cleaner than the last.'],
    [{ wrong: 'more better', right: 'better', note: 'Never double the comparison.' }],
    'Compare two tools you use at work in three sentences.',
    'Write a two-sentence product comparison for a client.',
    [Q('good →', ['gooder', 'more good', 'better', 'best'], 2, 'Irregular: better.'),
     Q('Correct:', ['more faster', 'faster', 'fastest than', 'more fast'], 1, 'Short adjective → -er.'),
     Q('"than" after comparative is…', ['optional', 'required for the comparison', 'a preposition of place', 'never used'], 1, 'bigger than X.'),
     Q('Choose: This is ___ than before.', ['difficulter', 'more difficult', 'most difficult', 'difficult more'], 1, 'Long adjective → more.')],
    'Pricing conversations live on comparative language.'),
  L('lesson-superlatives', 'Superlatives', 'comparatives-superlatives',
    'The extreme in a group: -est or most + adjective, with the.',
    'Superlatives anchor claims: "the fastest turnaround in our segment".',
    'the + -est/most; irregular: best, worst, furthest.',
    ['the tallest building', 'the best day', 'the most interesting book'],
    ['That was the worst meeting ever.', 'She\'s the most reliable person on the team.', 'This is the cheapest option.'],
    ['Our strongest quarter yet.', 'The most critical dependency is auth.', 'He\'s the best negotiator we have.'],
    [{ wrong: 'most fastest', right: 'fastest', note: 'No double superlative.' }],
    'Describe the best/worst/most interesting part of your year.',
    'Write a one-line superlative claim for your product.',
    [Q('bad →', ['baddest', 'worse', 'worst', 'most bad'], 2, 'Irregular: worst.'),
     Q('Correct:', ['the most tallest', 'the tallest', 'tallest than', 'most tall'], 1, 'Short → -est.'),
     Q('Superlatives need…', ['a', 'the', 'an', 'no article'], 1, 'Always "the".'),
     Q('Choose: ___ player on the team.', ['The better', 'The best', 'Most best', 'Best than'], 1, 'the best.')],
    'Marketing claims need superlatives that hold up.'),
  L('lesson-conditionals', 'Conditionals', 'conditionals',
    'If-clauses for real, hypothetical and impossible past conditions.',
    'Negotiation runs on conditionals: "If you extend the deadline, we can reduce the price."',
    'Zero: if + present, present. First: if + present, will. Second: if + past, would. Third: if + past perfect, would have + participle.',
    ['If it rains, we stay in.', 'If I were you, I\'d wait.', 'If she had known, she would have come.'],
    ['If you order today, it ships free.', 'If I had more time, I\'d learn piano.', 'If we\'d left earlier, we wouldn\'t have missed it.'],
    ['If you sign this week, we\'ll add a month free.', 'If we lowered the price, would you commit?', 'If we had tested more, the bug wouldn\'t have shipped.'],
    [{ wrong: 'If I will go, I will call.', right: 'If I go, I will call.', note: 'No will inside the if-clause.' },
     { wrong: 'If I would have known…', right: 'If I had known…', note: 'Third conditional: had + participle in the if-clause.' }],
    'Say one real and one hypothetical offer you could make a client.',
    'Write a two-line conditional offer for a proposal email.',
    [Q('First conditional:', ['If it rains, I would stay', 'If it rains, I will stay', 'If it will rain, I stay', 'If it rained, I stay'], 1, 'present + will.'),
     Q('Second conditional verb form:', ['if + present', 'if + past → would', 'if + had', 'if + will'], 1, 'Hypothetical → past + would.'),
     Q('"If I ___ you":', ['was', 'am', 'were', 'be'], 2, 'were for all persons — subjunctive.'),
     Q('Third conditional result clause:', ['would + base', 'would have + participle', 'will have + base', 'had + participle'], 1, 'would have gone.')],
    'Every counteroffer you will ever make is a conditional sentence.'),
  L('lesson-passive-voice', 'Passive Voice', 'passive-voice',
    'Focus on the receiver of the action: "The report was approved."',
    'Formal reporting, incident writing and diplomacy all need the passive.',
    'be + past participle; agent with by is optional and often omitted.',
    ['The cake was eaten.', 'English is spoken here.', 'The door was closed.'],
    ['My car was stolen last night.', 'The email was sent this morning.', 'Mistakes were made.'],
    ['The contract was signed yesterday.', 'Two candidates were shortlisted.', 'Payment will be released on approval.'],
    [{ wrong: 'The work was finished by me yesterday.', right: 'I finished the work yesterday.', note: 'Prefer active when the actor matters — passive for focus/diplomacy.' }],
    'Describe your morning routine in passive voice, three sentences.',
    'Rewrite two active project sentences as passive; note when each is better.',
    [Q('be + ___', ['base', '-ing', 'past participle', 'past'], 2, 'Participle.'),
     Q('Active → passive: "She wrote it."', ['It was write by her', 'It was written by her', 'It is wrote by her', 'It written'], 1, 'was + written.'),
     Q('Use passive when…', ['always', 'the actor is unknown/unimportant', 'in informal speech', 'never'], 1, 'Focus on the receiver.'),
     Q('Correct:', ['The house is being built', 'The house is being build', 'The house is being building', 'The house been built'], 0, 'being + participle.')],
    '"The deployment was rolled back" — blame-free incident reporting.'),
  L('lesson-reported-speech', 'Reported Speech', 'reported-speech',
    'Report what others said: backshift tenses and adjust pronouns/time words.',
    'Relaying client words to your team accurately is a daily need.',
    'present → past, past → past perfect, will → would; "today" → "that day".',
    ['He said he was tired.', 'She said she\'d call.', 'They said they had finished.'],
    ['She told me the flight was delayed.', 'He said he would join the call.', 'They said the project had ended.'],
    ['The client said the budget was approved.', 'She mentioned that the timeline had moved.', 'He said they would renew the contract.'],
    [{ wrong: 'He said that he is coming.', right: 'He said he was coming.', note: 'Backshift present → past after said.' }],
    'Report three things a colleague told you today.',
    'Write a two-line summary of what a client said on a call.',
    [Q('"I am busy" → He said he ___ busy.', ['is', 'was', 'be', 'has been'], 1, 'Backshift am → was.'),
     Q('"I will go" → She said she ___ go.', ['will', 'would', 'shall', 'goes'], 1, 'will → would.'),
     Q('Correct reporting verb for requests:', ['She said me to wait', 'She told me to wait', 'She told to me wait', 'She say me wait'], 1, 'told + object + to-infinitive.'),
     Q('"yesterday" in reported speech →', ['yesterday', 'the day before', 'tomorrow', 'last day'], 1, 'Shift time expressions.')],
    'Accurate relaying of client words builds trust.'),
  L('lesson-relative-clauses', 'Relative Clauses', 'relative-clauses',
    'Add information about a noun with who/which/that/whose/where.',
    'Relative clauses are how simple sentences become professional ones.',
    'who = people, which = things, that = both (defining only); commas around non-defining clauses.',
    ['The man who called left.', 'The book that I bought is good.', 'My car, which is old, still works.'],
    ['The person who interviewed me was kind.', 'The report that you sent needs work.', 'Our product, which launched in June, is growing.'],
    ['The vendor who quoted lowest won.', 'The proposal, which we reviewed twice, is ready.', 'She\'s the consultant whose advice we followed.'],
    [{ wrong: 'The man which came…', right: 'The man who came…', note: 'who for people.' }],
    'Describe a colleague, a tool and a client using who/which/that.',
    'Write two sentences with non-defining clauses (commas).',
    [Q('For people use…', ['which', 'who', 'where', 'what'], 1, 'who.'),
     Q('Non-defining clauses need…', ['that', 'commas', 'no pronoun', 'capital letters'], 1, 'Commas, and "which" not "that".'),
     Q('"whose" expresses…', ['place', 'time', 'possession', 'reason'], 2, 'Possession.'),
     Q('Choose: The report ___ you sent is wrong.', ['who', 'which', 'whose', 'where'], 1, 'which (or that).')],
    'Every well-built spec sentence uses relative clauses.'),
  L('lesson-gerunds', 'Gerunds', 'gerunds-infinitives',
    'Verb-ing used as a noun: "Running is fun." / "I enjoy reading."',
    'Choosing -ing vs to-infinitive after verbs is one of English\'s hard edges.',
    'After enjoy/mind/avoid/suggest/finish/preposition → -ing.',
    ['Swimming is fun.', 'I enjoy reading.', 'Thanks for coming.'],
    ['I\'m looking forward to meeting them.', 'She suggested delaying the launch.', 'I don\'t mind working late.'],
    ['We discussed extending the contract.', 'He avoided answering the question.', 'I recommend reviewing the terms.'],
    [{ wrong: 'I am looking forward to meet you.', right: 'I look forward to meeting you.', note: '"to" here is a preposition → -ing.' },
     { wrong: 'She suggested me to wait.', right: 'She suggested that I wait. / She suggested waiting.', note: 'suggest never takes object + to.' }],
    'Say three things you enjoy/avoid/mind doing.',
    'Write a sentence with "look forward to" correctly.',
    [Q('enjoy + ___', ['to read', 'reading', 'read', 'reads'], 1, 'Gerund after enjoy.'),
     Q('Correct:', ['I suggest to wait', 'I suggest waiting', 'I suggest you to wait', 'I suggest for wait'], 1, 'suggest + -ing.'),
     Q('After a preposition use…', ['to-infinitive', 'gerund', 'past', 'base'], 1, 'Preposition + -ing.'),
     Q('"look forward to" + ___', ['meet', 'meeting', 'met', 'to meet'], 1, 'to is a preposition here.')],
    '"Looking forward to meeting you" — the most-missed phrase in business email.'),
  L('lesson-infinitives', 'Infinitives', 'gerunds-infinitives',
    'to + verb for purpose, after certain verbs, and after adjectives.',
    '"I want that you come" fails; "I want you to come" works.',
    'want/ask/tell/expect + object + to-infinitive; purpose = to + verb; after let/make → bare infinitive.',
    ['I want to learn.', 'She asked me to wait.', 'It\'s hard to say.'],
    ['I came here to talk to you.', 'He told me to call back.', 'It\'s easy to use.'],
    ['We need the vendor to confirm.', 'I expect the client to push back.', 'Let me explain the pricing.'],
    [{ wrong: 'I want that you send it.', right: 'I want you to send it.', note: 'want + object + to-infinitive.' },
     { wrong: 'He made me to wait.', right: 'He made me wait.', note: 'make/let + bare infinitive.' }],
    'Say three sentences about things you want/expect your team to do.',
    'Write two sentences using "ask … to" and "tell … to".',
    [Q('want + object + ___', ['base', 'to-infinitive', 'gerund', 'past'], 1, 'want you to go.'),
     Q('After "make/let" use…', ['to-infinitive', 'bare infinitive', 'gerund', 'past'], 1, 'Let me explain.'),
     Q('Purpose:', ['I came for talk', 'I came to talk', 'I came talking', 'I came talked'], 1, 'to + verb.'),
     Q('Correct:', ['She suggested me to go', 'She asked me to go', 'She said me to go', 'She wants that I go'], 1, 'ask + object + to.')],
    'Object + infinitive runs through every delegation sentence you write.'),
  L('lesson-participles', 'Participles', 'participles',
    'Present (-ing) and past (-ed/-en) participles as adjectives and reduced clauses.',
    '"I am boring" vs "I am bored" is a meaning flip you cannot afford.',
    '-ing describes the thing causing the feeling; -ed describes the person feeling it.',
    ['The movie is boring.', 'I am bored.', 'Broken glass.'],
    ['It was a confusing meeting.', 'She looked exhausted.', 'Running late, he skipped breakfast.'],
    ['The revised proposal is convincing.', 'Interested parties should reply by Friday.', 'Having reviewed the contract, we approved it.'],
    [{ wrong: 'I am interesting in this role.', right: 'I am interested in this role.', note: 'Person feels it → -ed.' }],
    'Describe something that is interesting and someone who is interested.',
    'Write a sentence starting with "Having finished…".',
    [Q('The lecture was ___.', ['bored', 'boring', 'bore', 'bores'], 1, 'It causes the feeling.'),
     Q('I am ___ in the project.', ['interesting', 'interested', 'interest', 'interests'], 1, 'Person feels it → -ed.'),
     Q('Reduced clause:', ['Running late, he left', 'Run late, he left', 'Ran late he left', 'To run late, he left'], 0, 'Participle phrase opener.'),
     Q('Past participle adjective:', ['a break window', 'a broken window', 'a breaking window', 'a broke window'], 1, 'broken.')],
    'Interview English lives or dies on -ed/-ing adjectives.'),
  L('lesson-clauses', 'Clauses', 'clauses',
    'Main clauses stand alone; subordinate clauses (noun, adverbial, relative) depend on one.',
    'Sentence variety = clause control; flat English = boring English.',
    'A subordinate clause has subject+verb but cannot stand alone; attach it to a main clause.',
    ['I know that she left.', 'When it rains, we stay home.', 'The man who called left.'],
    ['I think that we should wait.', 'Because the deal fell through, we regrouped.', 'What he said surprised everyone.'],
    ['We believe that the terms are fair.', 'When the audit completes, we will invoice.', 'What the client wants is clarity.'],
    [{ wrong: 'Because I was tired. (fragment as a full sentence)', right: 'Because I was tired, I left early.', note: 'Subordinate clause needs a main clause.' }],
    'Combine two short ideas into one sentence with a because-clause.',
    'Write a sentence starting with "What we need is…".',
    [Q('A subordinate clause…', ['stands alone', 'needs a main clause', 'has no verb', 'is a phrase'], 1, 'It depends.'),
     Q('"What she said" is a…', ['main clause', 'noun clause', 'phrase', 'sentence'], 1, 'Acts as a noun.'),
     Q('Which is a fragment?', ['I slept.', 'When I slept.', 'I slept early.', 'Sleeping helps.'], 1, 'Subordinate clause alone = fragment.'),
     Q('Choose the noun clause:', ['after the meeting', 'that he resigned', 'very quickly', 'in spite of rain'], 1, 'that-clause = noun clause.')],
    'Clause control is the skeleton of formal writing.'),
  L('lesson-compound-sentences', 'Compound Sentences', 'compound-complex-sentences',
    'Join independent clauses with a coordinator or semicolon.',
    'Comma splices ("I went, he left") are the most common punctuation-level error.',
    'Independent clause + comma + and/but/so/yet/or; or semicolon without a conjunction.',
    ['I came, and she left.', 'It rained, so we stayed.', 'He tried; he failed.'],
    ['The price was high, but we signed anyway.', 'I called twice, and nobody picked up.', 'The launch slipped; the team adapted.'],
    ['Costs rose, yet margins held.', 'We offered a discount, and they accepted.', 'The audit is done; the report follows.'],
    [{ wrong: 'We finished the work, we went home.', right: 'We finished the work, and we went home.', note: 'Comma splice → add a coordinator or use a semicolon.' }],
    'Join three pairs of short sentences with and/but/so.',
    'Write two sentences using a semicolon.',
    [Q('Fix the splice "I ran, I fell":', ['I ran I fell', 'I ran, and I fell', 'I ran; fell I', 'I ran fell'], 1, 'Coordinator fixes it.'),
     Q('A semicolon joins…', ['a clause and a phrase', 'two independent clauses', 'two fragments', 'a subject and verb'], 1, 'Two complete sentences.'),
     Q('Coordinator for contrast:', ['and', 'so', 'but', 'or'], 2, 'but/yet.'),
     Q('Choose: "It was late, ___ we kept working."', ['because', 'but', 'although', 'since'], 1, 'Contrast between equals → but.')],
    'Compound sentences are the cheapest upgrade to your writing.'),
  L('lesson-complex-sentences', 'Complex Sentences', 'compound-complex-sentences',
    'Main clause + subordinate clauses: the architecture of fluent speech.',
    'B2→C1 is measured largely by comfortable subordination.',
    'Vary clause order: "Although X, Y" and "Y although X" both work — punctuate the fronted clause.',
    ['When she arrived, I left.', 'I left because she arrived.', 'The report, which was late, was approved.'],
    ['If the client pushes back, we hold the price.', 'We succeeded because we prepared.', 'The vendor, who had underbid, delivered late.'],
    ['Although the timeline is tight, we can deliver.', 'We priced it higher because the scope grew.', 'The contract, which legal reviewed, is ready.'],
    [{ wrong: 'Although it was late, but we continued.', right: 'Although it was late, we continued.', note: 'One connector only.' }],
    'Say one complex sentence about your work using although and one using because.',
    'Write two complex sentences; front the subordinate clause once.',
    [Q('A complex sentence has…', ['two main clauses', 'a main + dependent clause', 'two phrases', 'one verb'], 1, 'Main + subordinate.'),
     Q('Fronted subordinate clause needs…', ['a comma', 'a semicolon', 'a colon', 'nothing'], 0, '"Although X, Y."'),
     Q('Choose correct:', ['Because tired, I left.', 'Because I was tired, I left.', 'I left, because tired.', 'Tired because left.'], 1, 'Full clause after because.'),
     Q('Subordinators include…', ['and', 'but', 'although', 'so'], 2, 'Subordinator.')],
    'Complex sentences are the single clearest signal of advanced English.'),
  L('lesson-parallel-structure', 'Parallel Structure', 'parallel-structure',
    'Items in lists and comparisons must take the same grammatical form.',
    '"Responsible for hiring, training and to manage budgets" reads broken to every hiring manager.',
    'Keep listed items in identical form: gerund+gerund+gerund, noun+noun+noun.',
    ['I like reading, swimming and running.', 'She is smart and kind.', 'To err is human; to forgive, divine.'],
    ['The job requires writing reports, leading meetings and mentoring juniors.', 'We value clarity, honesty and speed.', 'He came, saw and conquered.'],
    ['The role covers planning sprints, reviewing code and shipping releases.', 'We need someone who can negotiate, present and close.', 'Fast, reliable and affordable — pick all three.'],
    [{ wrong: 'She likes swimming, to read and running.', right: 'She likes swimming, reading and running.', note: 'Same form across the list.' }],
    'List three of your job responsibilities in parallel -ing form.',
    'Write a parallel-structure bullet list of three skills.',
    [Q('Correct:', ['reading, to swim, running', 'reading, swimming, running', 'read, swim, run to', 'reads, swims, runs'], 1, 'All gerunds.'),
     Q('Parallelism applies to…', ['only nouns', 'any matched list items', 'only verbs', 'adjectives only'], 1, 'Any series.'),
     Q('"not only X but also Y" requires…', ['different forms', 'parallel forms', 'no verb', 'a question'], 1, 'Parallel.'),
     Q('Fix: "I want to learn, earning and to grow"', ['to learn, to earn, to grow', 'learn, earn, grow', 'learning, earning, growing', 'to learn, earn and grow'], 3, 'Shared to + parallel bases.')],
    'CV bullets and slide titles are judged on parallelism.'),
  L('lesson-emphasis', 'Emphasis', 'emphasis-inversion',
    'Highlight what matters with clefts, do-emphasis and fronting.',
    'Saying "What we need is…" focuses attention better than repeating yourself.',
    'Cleft: It is/was + focus + that/who; What-clause + be + focus; do/does/did + base verb for emphatic statements.',
    ['It was John who called.', 'What I need is sleep.', 'I do like it!'],
    ['What surprised me was the price.', 'It\'s the support that matters.', 'I did warn you.'],
    ['What the client wants is predictability.', 'It was the timeline that killed the deal.', 'We do offer post-launch support.'],
    [{ wrong: 'It is me who is responsible. (acceptable) vs What responsible is me ✗', right: 'What I am responsible for is the release.', note: 'Clefts need full clause structure.' }],
    'Emphasise one fact about your project using "What … is …".',
    'Write two cleft sentences about a recent decision.',
    [Q('"___ I need is a break."', ['It', 'What', 'That', 'This'], 1, 'What-cleft.'),
     Q('Emphatic do:', ['I do agree.', 'I do agreed.', 'I am agree.', 'I doing agree.'], 0, 'do + base.'),
     Q('It-cleft focuses on…', ['the verb', 'a noun phrase', 'the subject only', 'punctuation'], 1, 'Focus a noun phrase.'),
     Q('Correct:', ['It was yesterday that he came.', 'It is yesterday that he come.', 'It was yesterday who came.', 'What yesterday that he came.'], 0, 'It was X that…')],
    'Clefts make presentations and emails land harder.'),
  L('lesson-inversion', 'Inversion', 'emphasis-inversion',
    'After negative/limiting adverbials the auxiliary inverts: "Never have I seen…"',
    'Inversion is the formal-register signature move.',
    'Never/Rarely/Seldom/Not only/No sooner/Hardly + auxiliary + subject.',
    ['Never have I been so tired.', 'Rarely do we see this.', 'Not only did he call, he visited.'],
    ['Hardly had I sat down when the phone rang.', 'Seldom does she complain.', 'Under no circumstances should you sign.'],
    ['Rarely has a vendor delivered this early.', 'Not only did they meet the deadline, they beat it.', 'No sooner had we launched than signups doubled.'],
    [{ wrong: 'Never I have seen this.', right: 'Never have I seen this.', note: 'Negative adverbial triggers inversion.' }],
    'Say one "Never have I…" sentence about your work experience.',
    'Write a sentence starting with "Not only".',
    [Q('After "Never" the order is…', ['subject + verb', 'auxiliary + subject', 'verb only', 'unchanged'], 1, 'Invert like a question.'),
     Q('Correct:', ['No sooner we had left than it rained.', 'No sooner had we left than it rained.', 'No sooner had we left when it rained.', 'No sooner we left than rained.'], 1, 'had + subject, then "than".'),
     Q('Inversion register is…', ['casual', 'formal/emphatic', 'slang', 'wrong'], 1, 'Formal emphasis.'),
     Q('"Hardly ___ I arrived when…"', ['have', 'had', 'did', 'was'], 1, 'had for earlier event.')],
    'One well-placed inversion makes boardroom English sound executive.'),
  L('lesson-subjunctive', 'Subjunctive', 'subjunctive',
    'Mandative "that he go", unreal "if I were", wishes and counterfactuals.',
    'Formal recommendations ("we propose that he be added") use it constantly.',
    'that + subject + base form after suggest/recommend/insist/demand; if I were; wish + past.',
    ['I suggest that he wait.', 'If I were rich…', 'I wish I knew.'],
    ['The doctor recommended that she rest.', 'If I were you, I\'d negotiate.', 'I wish it were Friday.'],
    ['We propose that the clause be removed.', 'The board insisted that he be informed.', 'I wish the timeline were longer.'],
    [{ wrong: 'I suggest that he goes.', right: 'I suggest that he go.', note: 'Mandative subjunctive = base form.' },
     { wrong: 'If I was you (informal ok, formal prefers were)', right: 'If I were you.', note: 'were in formal hypothetical.' }],
    'Make two formal recommendations with "suggest/insist that…".',
    'Write a proposal line using "we propose that… be".',
    [Q('Mandative subjunctive form:', ['he goes', 'he go', 'he going', 'he to go'], 1, 'Base form.'),
     Q('Formal hypothetical: "If I ___ taller"', ['am', 'was', 'were', 'be'], 2, 'were.'),
     Q('Verbs triggering subjunctive:', ['suggest, insist, recommend', 'want, like, enjoy', 'all verbs', 'modals'], 0, 'Mandative verbs.'),
     Q('Correct:', ['I wish I was rich (formal)', 'I wish I were rich', 'I wish I be rich', 'I wish I will be rich'], 1, 'wish + were.')],
    'The subjunctive quietly marks educated formal English.'),
  L('lesson-advanced-punctuation', 'Advanced Punctuation', 'advanced-punctuation',
    'Semicolons, colons, dashes and parenthetical commas for precision.',
    'Punctuation controls tone in executive writing more than vocabulary does.',
    'Semicolon = two related sentences; colon = introduces explanation/list; dash = informal emphasis; commas set off parentheticals.',
    ['I came; I saw; I conquered.', 'There is one rule: be on time.', 'My brother — the tall one — called.'],
    ['It\'s simple: we ran out of time.', 'The result, surprisingly, was positive.', 'She knows her stuff; trust her.'],
    ['The verdict is clear: the pilot worked.', 'Q3 was strong; Q4 looks stronger.', 'The plan — though risky — is worth it.'],
    [{ wrong: 'The reason is: because he left.', right: 'The reason is that he left. / He left; that\'s the reason.', note: 'Don\'t double-mark with colon + because.' }],
    'Say aloud two sentences that would use a semicolon and a colon.',
    'Write three sentences: one each with semicolon, colon, dash.',
    [Q('Semicolon joins…', ['phrase + clause', 'two independent clauses', 'two fragments', 'subject + object'], 1, 'Two full sentences.'),
     Q('A colon introduces…', ['a contrast', 'an explanation or list', 'a question', 'a name only'], 1, 'Explanation/list.'),
     Q('Parenthetical commas set off…', ['verbs', 'inserted information', 'questions', 'articles'], 1, 'Inserted info.'),
     Q('Choose: "One thing matters ___ trust."', [';', ':', ',', '-?'], 1, 'Colon introduces the answer.')],
    'Precision punctuation is the cheapest way to look senior on paper.'),
  L('lesson-register-grammar', 'Register-Sensitive Grammar', 'register-grammar',
    'The same meaning wears different grammar: "Gimme a sec" vs "I would appreciate a moment."',
    'Register control is explicitly a mastery skill (§23).',
    'Formal register drops contractions, front-loads politeness markers, prefers passive/nominal forms; casual allows ellipsis and slang.',
    ['Casual: "No clue." → Formal: "I do not know."', 'Casual: "Can\'t make it." → Formal: "I am unable to attend."', 'Casual: "Whatever." → Formal: "I have no strong preference."'],
    ['Casual: "Shoot me the file." → Professional: "Could you send me the file?"', 'Casual: "Gonna be late." → Formal: "I will be delayed."', 'Casual: "Wanna hop on a call?" → Professional: "Would you be available for a call?"'],
    ['Casual: "Fix it asap." → Professional: "Please prioritise this."', 'Casual: "That won\'t work." → Executive: "That approach presents challenges."', 'Casual: "No idea." → Executive: "I need to look into that before committing."'],
    [{ wrong: 'Using "gonna" in a proposal.', right: '"going to" or restructure entirely.', note: 'Match grammar to register, not just words.' }],
    'Say "I need a minute" in casual, professional and executive register.',
    'Rewrite two chat messages for a formal email.',
    [Q('Formal register typically…', ['uses contractions', 'avoids contractions', 'uses slang', 'drops subjects'], 1, 'Full forms.'),
     Q('"Kindly revert" is…', ['universal formal English', 'Indian officialese — use "please reply"', 'casual', 'slang'], 1, 'Dated officialese.'),
     Q('Casual ellipsis drops…', ['verbs', 'subjects/auxiliaries', 'nouns', 'prepositions'], 1, '"Coming?" = Are you coming?'),
     Q('Executive phrasing for "bad idea":', ['terrible', 'that approach presents challenges', 'gonna fail', 'stupid'], 1, 'Diplomatic hedging.')],
    'The §23 register-switching module drills this daily.'),
  L('lesson-style', 'Style & Economy', 'register-grammar',
    'Say more with less: cut filler phrases, nominalisations and hedges.',
    'Executive readers stop reading bloated sentences.',
    'Prefer verbs over noun phrases ("decide" not "make a decision" where possible), cut "in order to" → "to", one hedge per sentence max.',
    ['due to the fact that → because', 'in order to → to', 'a large number of → many'],
    ['at this point in time → now', 'in the event that → if', 'has the ability to → can'],
    ['conduct an analysis of → analyse', 'reach a conclusion → conclude', 'make a payment → pay'],
    [{ wrong: 'I am writing this email in order to inform you that…', right: 'I\'m writing to let you know…', note: 'Cut preamble.' }],
    'Say a verbose sentence, then say it in half the words.',
    'Cut this to half its length: "In the event that there is a delay in the delivery of the materials, we would like to request that you inform us at the earliest possible opportunity."',
    [Q('Best cut of "in order to":', ['so as to', 'to', 'for to', 'in order that'], 1, 'to.'),
     Q('"at this point in time" →', ['presently', 'now', 'currently always wrong', 'today'], 1, 'now.'),
     Q('Nominalisation means…', ['shortening words', 'turning verbs into nouns', 'adding adjectives', 'using slang'], 1, '"decision" from decide.'),
     Q('Prefer: "We conducted an investigation" →', ['We investigated.', 'We did an investigation.', 'An investigation was conducted by us.', 'Investigating we did.'], 0, 'Verb form is leaner.')],
    'Every business email improves when you cut a third of it.'),
  L('lesson-tense-consistency', 'Tense Consistency', 'narrative-consistency',
    'Pick a time frame and hold it while narrating.',
    'Tense drift mid-story ("I was walking… then I see this guy") confuses listeners about when things happened.',
    'Establish the anchor tense in the first clause; shift only when the time frame genuinely changes; return deliberately.',
    ['Yesterday I walked home and bought groceries.', 'She said she was tired and went home.', 'Every morning I stretch and meditate.'],
    ['We were discussing the rollout when the server crashed — and then everything stopped.', 'I grew up in Chennai, but these days I live alone.', 'He pitched, they loved it, and we signed.'],
    ['Last quarter we missed the target, so this quarter we doubled outbound.', 'I had prepared the deck, but the meeting moved.', 'While I was reviewing the logs, the alert fired again.'],
    [{ wrong: 'Yesterday I go to the market and I buy vegetables.', right: 'Yesterday I went to the market and bought vegetables.', note: 'Keep the past anchor through the whole narrative.' }],
    'Tell a 30-second story about a problem you solved — keep one tense anchor.',
    'Write a five-sentence incident timeline in consistent past tense.',
    [Q('Tense anchor means…', ['never changing tense', 'a governing time frame for the narrative', 'only past tense', 'using continuous forms'], 1, 'Anchor + deliberate shifts.'),
     Q('Correct:', ['I was walking and I see him', 'I was walking and I saw him', 'I am walking and I saw', 'I walk and saw'], 1, 'Keep the frame.'),
     Q('Shifting tenses is OK when…', ['never', 'the time frame genuinely changes', 'mid-clause', 'for style'], 1, 'Deliberate, signalled shifts.'),
     Q('"had + participle" inside a past story marks…', ['the main events', 'an earlier background event', 'the future', 'a habit'], 1, 'Earlier event.')],
    'Storytelling skills (§10, §16) depend on this anchor.'),
  L('lesson-indian-english-patterns', 'Indian English Patterns', 'indian-english-repair',
    'Repair the regional patterns that read as errors internationally — without erasing your voice.',
    'The goal is informed choice: know when "prepone" is fine (India) and when it isn\'t (international client).',
    'Target the documented set: discuss about, one of my + singular, today morning, I have a doubt, I am having, do one thing, revert back, cope up with, years back, sentence-final only/itself, kind-ly officialese, prepone, good name.',
    ['discuss about → discuss', 'today morning → this morning', 'one of my friend → one of my friends'],
    ['revert back → get back / reply', 'I have a doubt → I have a question', 'cope up with → cope with'],
    ['do the needful → please handle X', 'prepone → move earlier / bring forward', 'years back → years ago'],
    [{ wrong: 'Please revert back.', right: 'Please reply / get back to me.', note: '"Revert" means return to a state — "revert back" is Indian officialese.' },
     { wrong: 'Out of station.', right: 'Out of town / travelling.', note: 'Railway-era phrase; opaque internationally.' }],
    'Say each corrected form aloud twice, then use it in your own sentence.',
    'Rewrite an email removing: kindly, revert back, do the needful, the same.',
    [Q('"Discuss about" should be…', ['discuss over', 'discuss (no preposition)', 'discuss on', 'discuss upon'], 1, 'Transitive verb.'),
     Q('"I have a doubt" internationally means…', ['a question', 'distrust or suspicion', 'certainty', 'a problem'], 1, 'Doubt ≠ question in standard usage.'),
     Q('"Prepone" is…', ['always wrong', 'valid Indian English, opaque elsewhere', 'British standard', 'American standard'], 1, 'Regional but real.'),
     Q('International form of "I am having a doubt":', ['I am having a question', 'I have a question', 'I am doubting', 'I had a doubt'], 1, 'Stative + doubt→question.')],
    '§42 detection is built into every speech and writing evaluation.'),
  L('lesson-phrasal-structures', 'Phrasal Structures', 'phrasal-structures',
    'Sentences are built from noun phrases, verb phrases, prepositional phrases — learn to see the chunks.',
    'Chunking is how you parse long business sentences and build your own without losing the thread.',
    'A phrase is a word group acting as one unit: noun phrase [the revised proposal], verb phrase [was quietly approved], prepositional phrase [by the board].',
    ['[The tall man] [opened] [the door].', '[In the morning] [we] [left].', '[A cup of coffee] [helps].'],
    ['[The new feature we shipped] [is getting] [good reviews].', '[By the end of the week] [the team] [had finished].', '[My manager\'s feedback] [was] [surprisingly direct].'],
    ['[The revised payment terms] [were accepted] [by both parties].', '[During the negotiation] [their position] [shifted noticeably].', '[A delay in delivery] [could trigger] [a penalty clause].'],
    [{ wrong: 'Parsing word-by-word instead of by phrase.', right: 'Read in chunks: [The vendor in Bangalore] [delivered] [ahead of schedule].', note: 'Phrase-level reading doubles comprehension speed.' }],
    'Break "The engineer who joined last month already fixed three critical bugs" into its phrases aloud.',
    'Write one sentence and bracket its noun, verb and prepositional phrases.',
    [Q('A phrase is…', ['a full sentence', 'a word group acting as one unit', 'a punctuation mark', 'a clause with subject+verb'], 1, 'Unit, no subject-verb pair.'),
     Q('"by the end of the week" is a…', ['noun phrase', 'verb phrase', 'prepositional phrase', 'clause'], 2, 'Preposition-headed phrase.'),
     Q('"The revised proposal" is a…', ['clause', 'noun phrase', 'sentence', 'verb phrase'], 1, 'Head noun + modifiers.'),
     Q('Phrases differ from clauses because they lack…', ['words', 'a subject-verb pair', 'meaning', 'prepositions'], 1, 'Clauses have subject+verb.')],
    'Chunked reading and writing underpins every complex-sentence skill.'),
];
