// spec §20 — idioms with literal meaning, real meaning, example, register caution.
export type IdiomSeed = { slug: string; idiom: string; literal: string; meaning: string; example: string; registerCaution: string; skillSlugs: string[] };

const I = (slug: string, idiom: string, literal: string, meaning: string, example: string, registerCaution = 'Safe in neutral registers; avoid in legal/formal writing.'): IdiomSeed =>
  ({ slug, idiom, literal, meaning, example, registerCaution, skillSlugs: ['idioms-use'] });

export const IDIOMS: IdiomSeed[] = [
  I('id-ballpark', 'ballpark figure', 'a number from baseball', 'a rough estimate', 'Can you give me a ballpark figure for the project?'),
  I('id-back-to-drawing', 'back to the drawing board', 'return to the design table', 'start over after failure', 'The client hated it — back to the drawing board.'),
  I('id-bandwagon', 'on the bandwagon', 'riding a parade wagon', 'following a trend', 'Everyone\'s jumping on the AI bandwagon.'),
  I('id-bite-bullet', 'bite the bullet', 'endure pain by biting', 'face a hard thing bravely', 'Let\'s bite the bullet and raise prices.'),
  I('id-blessing-disguise', 'a blessing in disguise', 'a hidden gift', 'a good thing that seemed bad', 'Losing that client was a blessing in disguise.'),
  I('id-boilerplate', 'boilerplate', 'standard plate text', 'generic reusable language', 'That whole section is boilerplate from the last contract.'),
  I('id-break-ice', 'break the ice', 'crack frozen water', 'start a conversation comfortably', 'A quick story breaks the ice in interviews.'),
  I('id-burn-bridges', 'burn bridges', 'destroy crossings', 'destroy a relationship permanently', 'Don\'t burn bridges when you resign.'),
  I('id-by-the-book', 'by the book', 'following the manual', 'strictly by the rules', 'Procurement does everything by the book.'),
  I('id-call-shots', 'call the shots', 'decide the firing', 'be the decision-maker', 'In this deal, the client calls the shots.'),
  I('id-cut-corners', 'cut corners', 'shave the edges', 'do it cheaply, skipping quality', 'We cut corners and the migration broke.'),
  I('id-dead-horse', 'beat a dead horse', 'whip a dead animal', 'argue a settled point', 'The deadline is fixed — don\'t beat a dead horse.'),
  I('id-devils-advocate', 'play devil\'s advocate', 'argue for the devil', 'argue the opposite to test thinking', 'Let me play devil\'s advocate on the timeline.'),
  I('id-elephant-room', 'the elephant in the room', 'a huge ignored animal', 'the obvious unspoken problem', 'Nobody mentioned the elephant in the room: churn.'),
  I('id-get-ball-rolling', 'get the ball rolling', 'start the ball moving', 'get things started', 'Let\'s get the ball rolling with a pilot.'),
  I('id-go-above', 'go above and beyond', 'exceed the map', 'do more than required', 'She goes above and beyond for clients.'),
  I('id-hit-ground', 'hit the ground running', 'land already sprinting', 'start productive immediately', 'We need someone who can hit the ground running.'),
  I('id-in-same-boat', 'in the same boat', 'sharing a vessel', 'in the same situation', 'We\'re in the same boat — understaffed.'),
  I('id-keep-loop', 'keep me in the loop', 'stay inside the circle', 'keep me informed', 'Keep me in the loop on the negotiation.'),
  I('id-last-straw', 'the last straw', 'the straw that broke the camel', 'the final tolerable problem', 'The third missed deadline was the last straw.'),
  I('id-learning-curve', 'steep learning curve', 'a hard climb', 'hard to learn quickly', 'There\'s a steep learning curve with the new stack.'),
  I('id-long-shot', 'a long shot', 'a distant arrow', 'low chance of success', 'It\'s a long shot, but we might win the bid.'),
  I('id-low-hanging', 'low-hanging fruit', 'easy fruit to pick', 'the easy wins first', 'Fixing typos is low-hanging fruit.'),
  I('id-move-needle', 'move the needle', 'shift the gauge', 'create real impact', 'Let\'s focus on what moves the needle.'),
  I('id-no-brainer', 'a no-brainer', 'needs no brain', 'an obvious decision', 'At that price it\'s a no-brainer.'),
  I('id-on-back-burner', 'on the back burner', 'at the rear of the stove', 'deprioritised', 'The redesign is on the back burner for now.'),
  I('id-on-fence', 'on the fence', 'sitting between two yards', 'undecided', 'The client is still on the fence.'),
  I('id-out-of-loop', 'out of the loop', 'outside the circle', 'uninformed', 'I was out of the loop on the pricing change.'),
  I('id-picture', 'the big picture', 'the whole image', 'the overall view', 'Let\'s step back and look at the big picture.'),
  I('id-pie-in-sky', 'pie in the sky', 'dessert in the clouds', 'unrealistic idea', 'A 50% discount is pie in the sky.'),
  I('id-pinch-salt', 'take it with a pinch of salt', 'season sceptically', 'don\'t fully believe it', 'Take his projections with a pinch of salt.'),
  I('id-pipe-dream', 'a pipe dream', 'an opium-pipe fantasy', 'an impossible plan', 'Bootstrapping to a billion is a pipe dream.'),
  I('id-play-hardball', 'play hardball', 'the tougher ball game', 'negotiate aggressively', 'They played hardball on the contract terms.'),
  I('id-pull-strings', 'pull strings', 'operate the puppet', 'use influence unofficially', 'He pulled strings to get the meeting.'),
  I('id-raise-bar', 'raise the bar', 'lift the standard', 'increase expectations', 'This release raises the bar for the product.'),
  I('id-read-between', 'read between the lines', 'find the hidden text', 'understand what\'s implied', 'Reading between the lines, they want to renegotiate.'),
  I('id-red-tape', 'red tape', 'bureaucratic ribbon', 'excessive bureaucracy', 'The visa process is full of red tape.'),
  I('id-rock-boat', 'rock the boat', 'shake the vessel', 'cause disruption', 'Don\'t rock the boat before the launch.'),
  I('id-rubber-stamp', 'rubber-stamp it', 'approve with a stamp', 'approve without scrutiny', 'The board just rubber-stamped the plan.'),
  I('id-rule-thumb', 'rule of thumb', 'measure by the thumb', 'a practical guideline', 'As a rule of thumb, double the estimate.'),
  I('id-safe-bet', 'a safe bet', 'a low-risk wager', 'a reliable choice', 'Hiring seniors is a safe bet.'),
  I('id-shot-dark', 'a shot in the dark', 'firing blind', 'a wild guess', 'My diagnosis was a shot in the dark.'),
  I('id-silver-lining', 'the silver lining', 'the cloud\'s bright edge', 'the positive side of a bad thing', 'The silver lining: we learned what not to do.'),
  I('id-skeleton-closet', 'skeletons in the closet', 'hidden corpses', 'embarrassing secrets', 'Every codebase has skeletons in the closet.'),
  I('id-sleep-on', 'sleep on it', 'decide overnight', 'delay a decision to think', 'Don\'t sign today — sleep on it.'),
  I('id-slip-through', 'slip through the cracks', 'fall through gaps', 'get missed by a system', 'That invoice slipped through the cracks.'),
  I('id-table-it', 'table the discussion', 'put it on the table', 'postpone the topic', 'Let\'s table this until Friday.'),
  I('id-test-waters', 'test the waters', 'feel the water first', 'try cautiously before committing', 'Let\'s test the waters with a pilot project.'),
  I('id-throw-towel', 'throw in the towel', 'boxer\'s surrender', 'give up', 'After six months, they threw in the towel.'),
  I('id-touch-base', 'touch base', 'tag the base', 'briefly reconnect', 'Let\'s touch base tomorrow morning.'),
  I('id-under-table', 'under the table', 'hidden below', 'unofficial/illegal payment', 'They wanted payment under the table — we refused.', 'Describes impropriety; never offer it.'),
  I('id-walk-fine', 'walk a fine line', 'balance on a wire', 'balance carefully between risks', 'We\'re walking a fine line between speed and quality.'),
];
