// spec §15 — ready TTS scripts for each listening mode. `accent` is a label +
// a neutral instructions string for the TTS provider (no caricature).

export type ListeningAccent =
  | 'indian' | 'general-american' | 'modern-british' | 'australian'
  | 'international-business' | 'neutral';

export type ListeningScript = {
  slug: string; mode: string; accent: ListeningAccent; title: string;
  speakers: string[];
  lines: { speaker: string; text: string }[];
  questions: { q: string; options?: string[]; answer: string }[];
  summaryReference: string;
  dictationTargets: string[];
};

export const ACCENT_INSTRUCTIONS: Record<ListeningAccent, string> = {
  'indian': 'Speak with a natural, educated Indian English accent.',
  'general-american': 'Speak with a neutral General American accent.',
  'modern-british': 'Speak with a natural modern British accent.',
  'australian': 'Speak with a natural general Australian accent.',
  'international-business': 'Speak clearly in international business English.',
  'neutral': 'Speak clearly and neutrally.',
};

const S = (
  slug: string, mode: string, accent: ListeningAccent, title: string,
  speakers: [string, string], lines: [string, string][],
  questions: [string, string, string[]?][],
  summaryReference: string, dictationTargets: [string, string],
): ListeningScript => ({
  slug, mode, accent, title, speakers: [...speakers],
  lines: lines.map(([speaker, text]) => ({ speaker, text })),
  questions: questions.map(([q, answer, options]) => ({ q, answer, options })),
  summaryReference, dictationTargets: [...dictationTargets],
});

export const LISTENING_SCRIPTS: ListeningScript[] = [
  // — Conversation comprehension —
  S('lc-commute', 'listen-conversation', 'general-american', 'The new commute',
    ['Asha', 'Ben'],
    [['Asha', 'Hey Ben, you look tired — rough morning?'],
     ['Ben', 'Yeah, the metro was packed. Took me almost an hour.'],
     ['Asha', 'Ouch. Have you tried leaving twenty minutes earlier?'],
     ['Ben', 'I keep meaning to. Maybe I\'ll just work from home on Fridays.'],
     ['Asha', 'Do it. I\'ve done it for a month now and it\'s the best part of my week.']],
    [['Why is Ben tired?', 'A crowded metro made his commute long', ['He slept badly', 'A crowded metro made his commute long', 'He worked late', 'He missed breakfast']],
     ['What does Asha suggest?', 'Leaving twenty minutes earlier', ['Driving instead', 'Leaving twenty minutes earlier', 'Taking a taxi', 'Quitting his job']],
     ['What is Ben considering?', 'Working from home on Fridays', ['Working from home on Fridays', 'Changing jobs', 'Cycling to work', 'Moving house']]],
    'Ben had a long commute because the metro was crowded; Asha suggested leaving earlier and Ben considered working from home on Fridays.',
    ['Took me almost an hour.', 'Maybe I\'ll just work from home on Fridays.']),
  S('lc-weekend', 'listen-conversation', 'modern-british', 'Weekend plans',
    ['Priya', 'Tom'],
    [['Priya', 'Any plans for the weekend, Tom?'],
     ['Tom', 'Thinking of a long walk on the Downs, if the rain holds off.'],
     ['Priya', 'Lovely. We\'re having a few people round on Saturday — fancy joining?'],
     ['Tom', 'Thanks! I\'d love to, as long as the weather plays along.']],
    [['What might Tom do?', 'A long walk on the Downs', ['Go shopping', 'A long walk on the Downs', 'Visit his parents', 'Sleep in']],
     ['What does Priya invite Tom to?', 'A gathering at her place on Saturday', ['A restaurant dinner', 'A gathering at her place on Saturday', 'A hike', 'A meeting']]],
    'Priya invited Tom to a gathering on Saturday; Tom may first walk the Downs weather permitting.',
    ['Fancy joining?', 'As long as the weather plays along.']),
  S('lc-project', 'listen-conversation', 'indian', 'Project update',
    ['Kavya', 'Rohan'],
    [['Kavya', 'Rohan, where are we on the vendor migration?'],
     ['Rohan', 'Data\'s moved; we\'re still validating the edge cases.'],
     ['Kavya', 'And the go-live date?'],
     ['Rohan', 'Thursday looks safe if QA signs off tonight.'],
     ['Kavya', 'Good. Loop me in if anything slips.']],
    [['What stage is the migration at?', 'Validating edge cases', ['Planning', 'Validating edge cases', 'Rolled back', 'Done']],
     ['When might they go live?', 'Thursday', ['Wednesday', 'Thursday', 'Friday', 'Next week']]],
    'Migration data moved; validation of edge cases remains; go-live Thursday pending QA sign-off.',
    ['We\'re still validating the edge cases.', 'Loop me in if anything slips.']),

  // — Phone call —
  S('lp-booking', 'listen-phone', 'modern-british', 'Booking a table',
    ['Caller', 'Restaurant'],
    [['Restaurant', 'Good afternoon, Bella Cucina.'],
     ['Caller', 'Hi, could I book a table for two for Saturday evening?'],
     ['Restaurant', 'Saturday… I can do seven or nine fifteen.'],
     ['Caller', 'Seven please, under the name Sharma.'],
     ['Restaurant', 'Done — table for two, seven pm Saturday, Sharma. See you then.']],
    [['What did the caller book?', 'A table for two on Saturday', ['A taxi', 'A table for two on Saturday', 'A meeting room', 'A delivery']],
     ['Which time was chosen?', '7 pm', ['6 pm', '7 pm', '9:15 pm', '8 pm']]],
    'Caller booked a table for two at 7pm Saturday under Sharma.',
    ['Could I book a table for two for Saturday evening?', 'Under the name Sharma.']),
  S('lp-complaint', 'listen-phone', 'general-american', 'Damaged delivery',
    ['Customer', 'Support'],
    [['Customer', 'Hi, my order arrived today but the box was crushed and one item is broken.'],
     ['Support', 'I\'m sorry about that. Can I have the order number?'],
     ['Customer', 'It\'s eight-three-four-five-one.'],
     ['Support', 'Thank you. I\'ll send a replacement today and email a return label for the damaged one.']],
    [['What went wrong?', 'The package was damaged', ['The order was late', 'The package was damaged', 'The price was wrong', 'The item was wrong']],
     ['What will support do?', 'Send a replacement and a return label', ['Refund the money', 'Send a replacement and a return label', 'Cancel the order', 'Call the courier']]],
    'A damaged delivery will be replaced; a return label is sent for the broken item.',
    ['My order arrived today but the box was crushed.', 'I\'ll send a replacement today.']),
  S('lp-inquiry', 'listen-phone', 'international-business', 'Pricing inquiry',
    ['Prospect', 'Sales'],
    [['Prospect', 'Hello, I saw your platform demo — what does it cost for a team of ten?'],
     ['Sales', 'For ten seats, the annual plan is about four hundred dollars a month.'],
     ['Prospect', 'Is there a discount for a two-year commitment?'],
     ['Sales', 'Yes — ten percent, and onboarding is included.']],
    [['What is being asked?', 'Pricing for a ten-person team', ['A demo booking', 'Pricing for a ten-person team', 'A refund', 'Support hours']],
     ['What discount is offered?', '10% for a two-year commitment', ['5% monthly', '10% for a two-year commitment', '20% upfront', 'None']]],
    'Ten seats cost about $400/month; a two-year term gets 10% off plus onboarding.',
    ['What does it cost for a team of ten?', 'Ten percent, and onboarding is included.']),

  // — Presentation / talk —
  S('lpr-results', 'listen-presentation', 'general-american', 'Quarterly results',
    ['Speaker', 'Speaker'],
    [['Speaker', 'Thanks for joining. Three quick points on Q3.'],
     ['Speaker', 'One: revenue grew twelve percent to four-point-two million.'],
     ['Speaker', 'Two: churn fell to two point one percent — our best quarter yet.'],
     ['Speaker', 'Three: we\'re opening the Chennai office in January.'],
     ['Speaker', 'Questions welcome — the full deck is in the shared folder.']],
    [['How much did revenue grow?', '12%', ['8%', '12%', '21%', '4.2%']],
     ['What was the churn figure?', '2.1%', ['1.2%', '2.1%', '4.2%', '12%']],
     ['What happens in January?', 'A Chennai office opens', ['A product launch', 'A Chennai office opens', 'A merger', 'A hiring freeze']]],
    'Q3 revenue +12% to $4.2M; churn 2.1% best ever; Chennai office opens January.',
    ['Revenue grew twelve percent to four-point-two million.', 'Churn fell to two point one percent.']),
  S('lpr-safety', 'listen-presentation', 'modern-british', 'Safety briefing',
    ['Trainer', 'Trainer'],
    [['Trainer', 'Quick safety briefing before we start.'],
     ['Trainer', 'Hard hats are mandatory beyond the yellow line.'],
     ['Trainer', 'The assembly point is the east car park, by the gate.'],
     ['Trainer', 'Any questions before we begin?']],
    [['Where are hard hats required?', 'Beyond the yellow line', ['Everywhere', 'Beyond the yellow line', 'In the canteen', 'At reception']],
     ['Where is the assembly point?', 'East car park by the gate', ['Main lobby', 'East car park by the gate', 'West exit', 'Roof']]],
    'Hard hats beyond the yellow line; assembly point is the east car park gate.',
    ['Hard hats are mandatory beyond the yellow line.', 'The assembly point is the east car park.']),

  // — Business meeting —
  S('lbm-budget', 'listen-business-meeting', 'international-business', 'Budget review',
    ['Chair', 'Finance'],
    [['Chair', 'Item two: the marketing budget.'],
     ['Finance', 'We\'re six percent over, driven by the campaign overage.'],
     ['Chair', 'Can we rebalance from events?'],
     ['Finance', 'Yes — moving thirty thousand covers it fully.'],
     ['Chair', 'Approved. Action: update the tracker by Friday.']],
    [['By how much is marketing over?', '6%', ['3%', '6%', '10%', '30%']],
     ['What is the decision?', 'Move 30,000 from events', ['Cut the campaign', 'Move 30,000 from events', 'Hire an agency', 'Defer to Q4']]],
    'Marketing is 6% over; 30k rebalanced from events; tracker updated by Friday.',
    ['We\'re six percent over, driven by the campaign overage.', 'Action: update the tracker by Friday.']),
  S('lbm-hiring', 'listen-business-meeting', 'general-american', 'Hiring plan',
    ['Manager', 'HR'],
    [['Manager', 'Next: engineering headcount for next half.'],
     ['HR', 'We proposed three: two backend, one data.'],
     ['Manager', 'Let\'s hold the data role until the budget review.'],
     ['HR', 'So two backend offers go out this week — agreed.']],
    [['How many roles were proposed?', 'Three', ['Two', 'Three', 'Four', 'One']],
     ['What was decided?', 'Two backend offers now; data role deferred', ['Hire all three now', 'Two backend offers now; data role deferred', 'Cancel hiring', 'Outsource']]],
    'Two backend offers proceed; the data role waits for the budget review.',
    ['Let\'s hold the data role until the budget review.', 'Two backend offers go out this week.']),

  // — Accent exposure — (same content across accents; play each)
  S('lae-meeting', 'listen-accent-exposure', 'australian', 'Accent set A',
    ['Speaker', 'Speaker'],
    [['Speaker', 'The meeting starts at ten sharp — don\'t be late.']],
    [['What should the listener do?', 'Arrive before ten', ['Call later', 'Arrive before ten', 'Bring lunch', 'Skip it']]],
    'Arrive before ten.', ['Don\'t be late.', 'The meeting starts at ten sharp.']),
  S('lae-report', 'listen-accent-exposure', 'modern-british', 'Accent set B',
    ['Speaker', 'Speaker'],
    [['Speaker', 'Could you email me the report by Friday, please?']],
    [['What is requested?', 'The report by Friday', ['A call Friday', 'The report by Friday', 'A meeting', 'Nothing']]],
    'Email the report by Friday.', ['Could you email me the report by Friday please?', 'By Friday, please.']),
  S('lae-parking', 'listen-accent-exposure', 'general-american', 'Accent set C',
    ['Speaker', 'Speaker'],
    [['Speaker', 'Parking is around the back; the front lot is for visitors only.']],
    [['Where can staff park?', 'Around the back', ['Front lot', 'Around the back', 'The street', 'The garage']]],
    'Staff park around the back; the front lot is for visitors.',
    ['Parking is around the back.', 'The front lot is for visitors only.']),

  // — Fast connected speech —
  S('lf-update', 'listen-fast-speech', 'general-american', 'Quick update',
    ['Speaker', 'Speaker'],
    [['Speaker', 'Quick heads-up: the client moved tomorrow\'s review to nine, so we\'ve gotta be there by eight forty-five, alright? They\'re gonna wanna see the final build, not the mock-ups.']],
    [['When is the review now?', 'Nine tomorrow', ['Five today', 'Nine tomorrow', 'Eight forty-five', 'Cancelled']],
     ['What do they want to see?', 'The final build', ['Mock-ups', 'The final build', 'A contract', 'A demo video']]],
    'Review moved to 9am; arrive by 8:45 with the final build.',
    ['The client moved tomorrow\'s review to nine.', 'They\'re gonna wanna see the final build.']),
  S('lf-lunch', 'listen-fast-speech', 'modern-british', 'Lunch plans',
    ['Speaker', 'Speaker'],
    [['Speaker', 'Wanna grab lunch? I\'m starving — been in back-to-back calls since eight and I\'ve literally not eaten a thing. How \'bout that new place on the corner?']],
    [['What does the speaker want?', 'Lunch at the new corner place', ['Coffee', 'Lunch at the new corner place', 'To cancel calls', 'A nap']]],
    'Speaker wants lunch at the new corner place — no food since 8am.',
    ['Wanna grab lunch?', 'Been in back-to-back calls since eight.']),

  // — Inference —
  S('li-hint', 'listen-inference', 'modern-british', 'The hint',
    ['Colleague', 'Colleague'],
    [['Colleague', 'This draft is… interesting. Would you mind if I made a few small tweaks before it goes out?']],
    [['What does the colleague really mean?', 'The draft needs changes', ['The draft is perfect', 'The draft needs changes', 'They refuse to send it', 'They wrote it themselves']]],
    'Politely saying the draft has problems and should be edited before sending.',
    ['Would you mind if I made a few small tweaks?', 'This draft is interesting.']),
  S('li-delay', 'listen-inference', 'general-american', 'The soft no',
    ['Client', 'Client'],
    [['Client', 'That price is a bit higher than we\'d budgeted. Can you send over some options and we\'ll circle back next quarter?']],
    [['What is implied?', 'They are unlikely to buy at this price', ['They accept the price', 'They are unlikely to buy at this price', 'They want a meeting today', 'Budget approved']]],
    'A polite deferral — the price is over budget and they won\'t commit now.',
    ['A bit higher than we\'d budgeted.', 'We\'ll circle back next quarter.']),

  // — Vocabulary in context —
  S('lvc-mitigate', 'listen-vocab-context', 'international-business', 'mitigate',
    ['Speaker', 'Speaker'],
    [['Speaker', 'To mitigate the risk, we added a second supplier and a buffer of two weeks\' stock. If one fails, the other covers us.']],
    [['What does "mitigate" mean here?', 'Reduce the harm', ['Eliminate entirely', 'Reduce the harm', 'Cause', 'Measure']]],
    'Mitigate = reduce harm; example: a second supplier plus buffer stock.',
    ['To mitigate the risk, we added a second supplier.', 'A buffer of two weeks\' stock.']),
  S('lvc-tentative', 'listen-vocab-context', 'general-american', 'tentative',
    ['Speaker', 'Speaker'],
    [['Speaker', 'The launch date is still tentative — engineering hasn\'t confirmed, so don\'t put it in the newsletter yet.']],
    [['What does "tentative" mean?', 'Not final', ['Secret', 'Not final', 'Cancelled', 'Early']]],
    'Tentative = not yet confirmed/final.',
    ['The launch date is still tentative.', 'Don\'t put it in the newsletter yet.']),

  // — Dictation —
  S('ld-s1', 'listen-dictation', 'general-american', 'Dictation set 1',
    ['Speaker', 'Speaker'],
    [['Speaker', 'Please send the updated invoice by close of business.'],
     ['Speaker', 'The vendor confirmed delivery for next Tuesday.']],
    [['Type what you hear (line 1)', 'Please send the updated invoice by close of business.'],
     ['Type what you hear (line 2)', 'The vendor confirmed delivery for next Tuesday.']],
    'Two business sentences.',
    ['Please send the updated invoice by close of business.', 'The vendor confirmed delivery for next Tuesday.']),
  S('ld-s2', 'listen-dictation', 'modern-british', 'Dictation set 2',
    ['Speaker', 'Speaker'],
    [['Speaker', 'We should probably double-check the figures before the call.'],
     ['Speaker', 'I\'ll loop in finance and get back to you.']],
    [['Type what you hear (line 1)', 'We should probably double-check the figures before the call.'],
     ['Type what you hear (line 2)', 'I\'ll loop in finance and get back to you.']],
    'Two office sentences.', ['We should probably double-check the figures.', 'I\'ll loop in finance and get back to you.']),
  S('ld-s3', 'listen-dictation', 'indian', 'Dictation set 3',
    ['Speaker', 'Speaker'],
    [['Speaker', 'The quarterly results will be announced on Friday morning.'],
     ['Speaker', 'Could you forward me the minutes of yesterday\'s meeting?']],
    [['Type what you hear (line 1)', 'The quarterly results will be announced on Friday morning.'],
     ['Type what you hear (line 2)', 'Could you forward me the minutes of yesterday\'s meeting?']],
    'Two corporate sentences.', ['The quarterly results will be announced on Friday morning.', 'Could you forward me the minutes?']),

  // — Speech repetition —
  S('lsr-s1', 'listen-speech-repetition', 'general-american', 'Repeat set 1',
    ['Speaker', 'Speaker'],
    [['Speaker', 'I need those figures checked and double-checked before noon.']],
    [['Repeat the sentence verbatim', 'I need those figures checked and double-checked before noon.']],
    'Repeat after the model.', ['I need those figures checked and double-checked before noon.', 'Before noon, please.']),
  S('lsr-s2', 'listen-speech-repetition', 'modern-british', 'Repeat set 2',
    ['Speaker', 'Speaker'],
    [['Speaker', 'There\'s no point rushing it if we\'re just going to redo it later.']],
    [['Repeat the sentence verbatim', 'There\'s no point rushing it if we\'re just going to redo it later.']],
    'Repeat after the model.', ['There\'s no point rushing it.', 'We\'d just redo it later.']),

  // — News —
  S('ln-economy', 'listen-news', 'modern-british', 'Business brief',
    ['Anchor', 'Anchor'],
    [['Anchor', 'In business news: the central bank held rates steady at four point two five percent, citing slowing inflation.'],
     ['Anchor', 'Analysts had expected a quarter-point cut; markets rose sharply on the announcement.']],
    [['What did the bank decide?', 'Hold rates at 4.25%', ['Cut rates', 'Hold rates at 4.25%', 'Raise rates', 'No decision']],
     ['How did markets react?', 'Rose sharply', ['Fell', 'Rose sharply', 'Flat', 'Closed early']]],
    'Bank held rates at 4.25% citing slowing inflation; markets rose.',
    ['Held rates steady at four point two five percent.', 'Markets rose sharply on the announcement.']),
  S('ln-tech', 'listen-news', 'general-american', 'Tech sector',
    ['Anchor', 'Anchor'],
    [['Anchor', 'Tech stocks rallied today as three major chipmakers reported better-than-expected quarterly earnings.'],
     ['Anchor', 'Supply constraints, however, continue to weigh on the automotive sector.']],
    [['Why did tech stocks rally?', 'Chipmakers beat earnings forecasts', ['New regulations', 'Chipmakers beat earnings forecasts', 'Rate cuts', 'A merger']],
     ['Which sector is struggling?', 'Automotive', ['Tech', 'Automotive', 'Retail', 'Energy']]],
    'Tech rallied on chipmaker earnings; automotive is constrained by supply.',
    ['Three major chipmakers reported better-than-expected earnings.', 'Supply constraints weigh on the automotive sector.']),

  // — Podcast —
  S('lpd-remote', 'listen-podcast', 'general-american', 'Remote work debate',
    ['Host A', 'Host B'],
    [['Host A', 'So — remote work: productivity killer or unlock?'],
     ['Host B', 'Honestly both. Deep work went up, but our onboarding really suffered.'],
     ['Host A', 'That\'s the tradeoff everyone forgets — you can\'t osmose culture over Zoom.'],
     ['Host B', 'Right. Hybrid works for us: juniors come in more, seniors get flexibility.']],
    [['What suffered in remote mode?', 'Onboarding', ['Sales', 'Onboarding', 'Deep work', 'Hiring']],
     ['What model do they use?', 'Hybrid — juniors in office more', ['Fully remote', 'Hybrid — juniors in office more', 'Fully in-office', 'Async only']]],
    'Remote boosted deep work but hurt onboarding; hybrid balances it.',
    ['Deep work went up, but onboarding really suffered.', 'You can\'t osmose culture over Zoom.']),
  S('lpd-ai', 'listen-podcast', 'modern-british', 'AI at work',
    ['Host A', 'Host B'],
    [['Host A', 'Is AI actually making your team faster?'],
     ['Host B', 'For boilerplate, absolutely. For judgement calls — it just moves the bottleneck to review.'],
     ['Host A', 'So the skill becomes reviewing, not writing?'],
     ['Host B', 'Exactly. Editing is the new drafting.']],
    [['Where does AI help most?', 'Boilerplate', ['Meetings', 'Boilerplate', 'Hiring', 'Design']],
     ['What\'s the new bottleneck?', 'Review', ['Writing', 'Review', 'Testing', 'Planning']]],
    'AI speeds boilerplate; the bottleneck moves to review — editing is the new drafting.',
    ['It just moves the bottleneck to review.', 'Editing is the new drafting.']),
];
