// spec §19 — high-value phrasal verbs taught in context.
export type PhrasalVerb = { slug: string; verb: string; meaning: string; contexts: string[]; examples: { daily: string; business: string }; register: string };

const P = (slug: string, verb: string, meaning: string, contexts: string[], daily: string, business: string, register = 'neutral'): PhrasalVerb =>
  ({ slug, verb, meaning, contexts, examples: { daily, business }, register });

export const PHRASAL_VERBS: PhrasalVerb[] = [
  P('pv-get-back', 'get back to', 'reply or return to a topic later', ['email', 'meetings'], 'I\'ll get back to you tonight.', 'I\'ll get back to you after checking with the team.'),
  P('pv-follow-up', 'follow up', 'contact again to check progress', ['sales', 'project management'], 'She followed up on her application.', 'I\'m following up on the proposal we sent.'),
  P('pv-look-into', 'look into', 'investigate', ['support', 'management'], 'I\'ll look into it this afternoon.', 'We\'re looking into the invoice discrepancy.'),
  P('pv-put-off', 'put off', 'postpone', ['planning'], 'Don\'t put off the dentist.', 'We put off the release until Friday.'),
  P('pv-come-up', 'come up', 'arise unexpectedly', ['scheduling', 'work'], 'Something came up at home.', 'An issue came up in the review.'),
  P('pv-come-up-with', 'come up with', 'produce an idea or plan', ['brainstorming'], 'She came up with a great name.', 'We came up with three options for the client.'),
  P('pv-figure-out', 'figure out', 'solve or understand', ['problem solving'], 'I can\'t figure out this settings page.', 'We figured out why the deploy failed.'),
  P('pv-point-out', 'point out', 'draw attention to', ['feedback', 'reviews'], 'He pointed out a typo.', 'She pointed out a flaw in the pricing.'),
  P('pv-work-out', 'work out', 'resolve or calculate', ['planning', 'math'], 'Let\'s work out the details.', 'We worked out a payment plan.'),
  P('pv-run-into', 'run into', 'encounter a problem or person', ['status updates'], 'I ran into an old friend.', 'We ran into a licensing issue.'),
  P('pv-deal-with', 'deal with', 'handle a problem or responsibility', ['work', 'customer service'], 'I deal with the difficult clients.', 'We\'re dealing with the fallout now.'),
  P('pv-bring-up', 'bring up', 'raise a topic', ['meetings'], 'He brought it up at dinner.', 'I\'d like to bring up the timeline.'),
  P('pv-break-down', 'break down', 'explain in parts; or fail', ['explaining', 'incidents'], 'The car broke down.', 'Let me break down the costs for you.'),
  P('pv-set-up', 'set up', 'arrange or configure', ['admin', 'tech'], 'I\'ll set up the call.', 'We set up a staging environment.'),
  P('pv-wrap-up', 'wrap up', 'finish', ['meetings'], 'Let\'s wrap up — it\'s late.', 'We wrapped up the audit yesterday.'),
  P('pv-take-on', 'take on', 'accept responsibility or work', ['capacity'], 'I can\'t take on more right now.', 'We took on three new clients this quarter.'),
  P('pv-carry-out', 'carry out', 'perform or execute', ['formal work'], 'They carried out the plan.', 'The audit was carried out last week.', 'professional'),
  P('pv-turn-down', 'turn down', 'reject an offer', ['offers', 'hiring'], 'She turned down the job.', 'We turned down their lowball offer.'),
  P('pv-catch-up', 'catch up', 'get current; reconnect', ['social', 'work'], 'Let\'s catch up over coffee.', 'I need to catch up on this thread.'),
  P('pv-fill-in', 'fill in', 'brief someone; or complete a form', ['handover'], 'Fill me in on what I missed.', 'Can you fill in the client on the delay?'),
  P('pv-go-ahead', 'go ahead', 'proceed', ['approvals'], 'Go ahead, I\'m listening.', 'They gave us the go-ahead on phase two.'),
  P('pv-keep-up', 'keep up', 'maintain pace', ['workload'], 'I can\'t keep up with the changes.', 'Demand grew faster than we could keep up with.'),
  P('pv-pick-up', 'pick up', 'collect; or learn quickly', ['logistics', 'learning'], 'I\'ll pick up the keys.', 'She picked up the new stack fast.'),
  P('pv-put-together', 'put together', 'assemble or create', ['documents', 'teams'], 'I put together a playlist.', 'We put together a proposal overnight.'),
  P('pv-run-through', 'run through', 'review quickly from start to end', ['rehearsal', 'meetings'], 'Let\'s run through the plan once.', 'I\'ll run through the agenda quickly.'),
  P('pv-spell-out', 'spell out', 'state clearly and explicitly', ['contracts', 'requirements'], 'Spell it out for me.', 'The contract spells out the payment terms.'),
  P('pv-think-over', 'think over', 'consider carefully', ['decisions'], 'Let me think it over.', 'We need time to think the offer over.'),
  P('pv-turn-up', 'turn up', 'arrive; or appear', ['meetings'], 'He didn\'t turn up for the call.', 'A cheaper option turned up.'),
  P('pv-walk-through', 'walk through', 'guide step by step', ['demos', 'docs'], 'Walk me through it.', 'I\'ll walk you through the onboarding.'),
  P('pv-work-around', 'work around', 'find a way past a constraint', ['constraints'], 'We worked around the missing API.', 'Let\'s work around the budget limit.'),
  P('pv-cut-down', 'cut down', 'reduce quantity', ['budgets', 'habits'], 'I\'m cutting down on coffee.', 'We need to cut down meeting time.'),
  P('pv-back-out', 'back out', 'withdraw from a commitment', ['deals'], 'He backed out at the last minute.', 'The investor backed out after due diligence.'),
  P('pv-check-in-on', 'check in on', 'briefly verify status', ['management'], 'Checking in on grandma.', 'I\'m checking in on the sprint progress.'),
  P('pv-come-across', 'come across', 'give an impression; or find by chance', ['impressions'], 'He comes across as confident.', 'I came across their product at a conference.'),
  P('pv-drop-off', 'drop off', 'decline; or deliver something', ['metrics'], 'Engagement dropped off.', 'User signups drop off at the payment step.'),
  P('pv-end-up', 'end up', 'reach a final outcome', ['results'], 'I ended up working late.', 'We ended up renewing for another year.'),
  P('pv-get-around', 'get around to', 'finally find time for', ['backlog'], 'I never got around to it.', 'We finally got around to fixing the search bug.'),
  P('pv-go-over', 'go over', 'review carefully', ['documents'], 'Let\'s go over your essay.', 'Let\'s go over the numbers once more.'),
  P('pv-hold-off', 'hold off', 'delay deliberately', ['decisions'], 'Hold off on buying.', 'We held off on hiring until funding closed.'),
  P('pv-iron-out', 'iron out', 'resolve small problems', ['finalisation'], 'Iron out the details.', 'We\'re ironing out the last issues before launch.'),
  P('pv-lay-out', 'lay out', 'present clearly in order', ['plans'], 'Lay out your proposal.', 'She laid out the roadmap clearly.'),
  P('pv-nail-down', 'nail down', 'finalise precisely', ['specs'], 'Let\'s nail down the date.', 'We nailed down the scope before pricing.'),
  P('pv-rule-out', 'rule out', 'eliminate as a possibility', ['diagnosis', 'decisions'], 'Don\'t rule it out yet.', 'We ruled out a security cause.'),
  P('pv-sign-off', 'sign off', 'approve formally', ['approvals'], 'Sign off on it.', 'Legal signed off on the terms.', 'professional'),
  P('pv-sort-out', 'sort out', 'resolve or organise', ['problems'], 'Sort out the mess.', 'We sorted out the billing confusion.'),
  P('pv-step-in', 'step in', 'intervene', ['escalation'], 'Thanks for stepping in.', 'Management stepped in to resolve the dispute.'),
];
